#include "pch.h"
#include "../Config/Config.h"
#include "ExeText.h"


#pragma region Kudos

std::vector<const char*> AdvertiseKudos
{
	/* Main menu */

	"\t0DNH NZP0K        ",
	"\t2N PEWNM      ",
	"\tYC0BEPGEHCTB0BATS                    ",
	"",
	"",
	"",
	"\tYX0D",

	/* Help & options */

	"\tQKCTPA MEHU",
	"",
	"",
	"",
	"\t0JVNN         ",
	"",

	/* Single player */

	"\tNZPA J0 NCT0PNN.          ",
	"\tBF60P CVEHF.                ",
	"\tNZPA J0 CTADNRM.            ",

	/* Some 2P mode stuff */

	"\tECTS 3 TNJA NZP.           ",
	"\tQT0 KAPT Z0H04H0N NZPF.      ",
	"\t4A0 YBELN4NTS    D0      (8) 4A0. ",

	/* Extras */

	"\tYC0BEPGEHCTB0BATS                    ",	//world ranking
	"\t0MAX0 06SRCHNT NZPY.          ",			//tutorial
	"\tJ0KA3ATS CJNC0K C06PAHHFX QM6LEM.     ", //emblem results
	"\tNZPATS 4EPE3 3AZPY3KY  ",				//DLC

	/* Memory card select (console leftover) */

	"\tBF60P JAMRTN         ",
	"\tHET MECTA DLR C03DAHNR OANLA.   ",

	/* File select */

	"\tBF60P OANLA.  ",
	"\tC03DATS H0BFN OANL",
	"\t3AZPY3NTS   ",
	"\tYDALNTS QT0T OANL?              ",
	"\tHET MECTA DLR C0XPAHEHNR 4A0.      ",

	/* Options */

	"\tCLYGAN MY3FKY.",
	"\tCTEPE0/M0H0 0JVNN.   ",
	"\tBF60P JPFWK0B             ",
	"\tBF60P R3FKA                        ",
	"\tBF60P OANLA.",
	"\tBF60P TEMF QKPAHA.       ",
	"\tBF60P  PAL TV YCTAH0B.",
	"\tCTEPE0 3BYK            ",
	"\tM0H0 3BYK                ",
	"\tJPFW0K BKL.  ",
	"\tJPFW0K BFKL.  ",
	"\tAHZLNNCKAR NCT0PNR",
	"\tRJ0HCKAR NCT0PNR.  ",
	"\tPYCCKNE CY6TNTPF ",
	"\t----------------  ",
	"\t----------------",
	"\t----------------",
	"\t-----------------",

	/* Sound test general */

	"\tBF60P MEL0DNN                        ",
	"\tBF60P JECHN NLN MY3FKN              ",

	/* Menu themes */

	"\tHAD0 3AZPY3NTS OANLF NCT0PNN",
	"\tBF60P NCT0PNN  ",
	"\t3AZPY3NTS NCT0PNN. ",
	"\tHEB03M0WH0 3AZPY3NTS      ",
	"\tHET OANL0B NCT0PNN.    ",
	"\tCKA4ATS C BE6CANTA         ",

	/* TV settings */

	"\tC0BMECTNM0CTS C TELEBN30P0M 60ZV",
	"\tJ0KAWEM KAPTNHKN HA 5 CEKYHD       ",
	"\tECLN K0PPEKTH0, 60 ZV C0BMECTNM0     ",
	"\t50ZV         ",
	"\tJ0KA3AH0 HA JAL TELEBN30PE        ",
	"\t60ZV         ",
	"\t60ZV TPE6YETCR             .",

	/* Separate string for Italian language */

	"",

	/* Progression percentage (unused) */

	"H0B",
	"10%JP0ND",
	"20%JP0ND",
	"30%JP0ND",
	"40%JP0ND",
	"50%JP0ND",
	"60%JP0ND",
	"70%JP0ND",
	"80%JP0ND",
	"90%JP0ND",

	/* Story select */

	"\tBF60P NCT0PNN  ",
	"\tHA4ATS CVEHY HA BF60P    ",

	/* Stage select */

	"\tBF60P CTADNN   ",
	"\tBF60P MNCCNN     ",

	/* Character select */

	"\tBF60P CTATYCA      ",

	/* Boss attack */

	"\tNZPA 60CC-CTADNN B NCT0PNN     ",

	/* Dreamcast 2P mode */

	"\tBF60P ZPYJJF C           D-pad.",
	"\tBF60P TNJA NZPF  ",
	"\tCLY4ANHAR NZPA          ",
	"\tBF60P CPAWEHNR        ",
	"\tBF60P CPAWEHNR        ",

	/* Kart racing */

	"\tB0DNTELS        ",
	"\tHAJPABLEHNE     ",
	"\t3AZPY3NTS  HAJPABLEHNE     ",
	"\tJP0BEPKA KAPTF JAMRTN",
	"\tBF60P 3AZPYWAEM0Z0 HAJP. ",
	"\tHE HANDEH0           ",
	"\tJP0BEPKA KAPTF JAMRTN",
	"\tHE HANDEH0             ",
	"\tBF60P 3AZPYWAEM0Z0 C06FT.",
	"\tX0TNTE NZPATS C QTNM C06FTNEM? ",
	"\tCTADNR J0KA HE D0CTYJHA    ",

	/* Sound test */

	"\t3BYK.JPNKLU4EHNE 2 CVEHF.    ",
	"\tLENTM0TNB 3BYK0B   ",
	"\tLENTM0TNB XB0CT0B.",
	"\tLENTM0TNB K0CTRGEK   ",
	"\tLENTM0TNB TEHEN     ",
	"\tLENTM0TNB QZMQHA    ",
	"\tLENTM0TNB PYMRH    ",
	"\tLENTM0TNB QMN    ",
	"\tMY3FKA DLR 60CC-CTADNN",

	"\tJ06EZ       6WM.",
	"\tKAHS0H      6MW.",
	"\tTUPSMA      6WM.",
	"\tMETAL ZABAHS 6WM.",
	"\t3ELEHFN LEC  6WM.",
	"\tTFKBEHH.X0LL 6WM.",
	"\tYLN4HAR MNCCNR 6WM.",
	"\tB0DHAR MNHA  6WM.",
	"\tKAPT 6WM.",
	"\tCKPFT. 6A3A 6WM.",
	"\tJEGEPA       6WM.",
	"\tKAMEPA CMEPT. 6WM.",
	"\tBE4HFN DBNZAT. 6WM.",
	"\tCTAD0       6WM.",
	"\tH0BNHKA      6WM.",
	"\tZ0HKA ONH. 6WM.",
	"\tB0P0TA    6WM.",
	"\tZP.LAZYHA  6WM.",
	"\t0KEAH JEC4.6WM.",
	"\tMAZNCTPALS      6WM.",
	"\tRNVEDELNTELS 6WM.",
	"\tJ0T.K0L0HNR 6WM.",
	"\t0PYWEHNR    6WM.",
	"\t3AL 0XPAHF    6WM.",
	"\t6EL.DWYHZLN  6WM.",
	"\t0ZPADA   6WM.",
	"\tK0CM0C    6WM.",
	"\tCTEHA K0CM. 6WM.",
	"\tONH.J0Z0HR  6WM.",
	"\tRDP0 JYGEK    6WM.",

	"\t4A0 CAD     6WM.",
	"\t4A0 DETCKNN CAD   6WM.",
	"\t4A0 L066N  6WM.",
	"\tHAZPAWDEHNE    6WM.",
	"\tHA4ALSHAR     6WM.",
	"\tC0CTR3AHNE     6WM.",
	"\tBX0D     6WM.",
	"\tDPAZ.Z0HKA 6WM.",
	"\tZPR3.TAHVF   6WM.",
	"\t6EZLEV  6WM.",
	"\tJ0LY4.HAZPADY 6WM.",
	"\tTEMHFN CAD  6WM.",
	"\tZEP0NCK.CAD 6WM. ",
	"\tTEMH.PENC 6WM.",
	"\tZEP0N.PENC 6WM",
	"\tMY3FKA OECTNBALR TEMH.CAD  ",
	"\tMY3FKA BECTNBALR ZEP0N.CAD.",
	"\t4A0 CAD     6WM.",

	"\tC06FT. 6WM",
	"\t04NCTNTS    CE.",
	"\tYB.CK0P0CTS.",
	"\tHEYR3BNM0CTS    CE.",
	"\tT0JNTS   CE.",
	"\t1   CE.",
	"\tJP0D0LWEHNE     CE.",

	"\tMY3FKA HA3B.",
	"\tMEHU QKPAHA 6WM.",
	"\t06Y4EHNE 6WM.",

	"\t3ELEH.X0LM 6WM.",

	/* Unlock stuff messages */

	"\tBF6EPETE CVEHY N3 NCT0PNN\nZEP0R               ",
	"\tBF6EPETE BPEMR ATAKN  \n60CC-CTADNN B NCT0PNN ZEP0R   ",
	"\tBF6EPETE CVEHY N3 NCT0PNN\nN3 TEMH0N NCT0PNN   ",
	"\tBF6EPETE BPEMR ATAKN  \nB0CC-CTADNR B TEMH0N NCT0PNN  ",
	"\tBCE BPEMR ATAKN B CTADNN   \nTEJEPS D0CTYJH0   ",
	"\tMNHN NZPA: KAPT PENC B TPEX  \nHAJPABLEHNRX D0CTYJHA    ",
	"\tMNHN NZPA: KAPT PENC   2P\nBEPCNR D0CTYJHA         ",
	"\tMNCCNN 3BYK0B JP0NDEHF!!!!!!        \nBF6EPNTE PA3HFE 3BYKN B     \n3BYK0B0M   2P PEWNME      ",
	"\tMNCCNR XB0CT0B JP0NDEHF!!!!!!!      \nBF6EPNTE PA3HFE MAGNHF B      \nXB0CT0B0M 2P PEWNME.    ",
	"\tMNCCNN K0CTRGEK JP0NDEHF!!!!!!!!!      \nBF6EPN PA3HFE K0CTRGKN B       \nK0CTRGKNH0M  2P PEWNME      ",
	"\tMNCCNN TEHEN JP0NDEHF!!!!!!!!!!!!     \nBF6EPNTE PA3HFE TEHN B       \nTEHEB0M     2P   PEWNME    ",
	"\tMNCCNN QZMQHA JP0NDEHF!!!!!!!!!!!!    \nBF6EPNTE PA3HFE MAGNHF B      \nB QZMAHCK0M 2P PEWNME      ",
	"\tMNCCNN PYMRH JP0NDEHF!!!!!!!!!!!!!1  \nBF6EPNTE DPYZNE PYMRHA B    \nPEWNME PYMRH    2P.            ",
	"\tMNCCNN 3BYK0B JP0NDEHF C  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \n3BYK0B0M   2P PEWNME      ",
	"\tMNCCNN XB0CT0B JP0NDEHF  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB PEWNME  2P XB0CT0B.    ",
	"\tJP0NDEHF BCE K0CTRGKNHF     \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nK0CTRGKNH0M  2P PEWNME      ",
	"\tJP0NDEHF BCE MNCCNN TEHEN  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nTEHEB0M     2P   PEWNME    ",
	"\tJP0NDEHF BCE QZMAHCKNE     \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB QZMAHCK0M 2P PEWNME      ",
	"\tJP0NDEHF BCE MNCCNN PYMRH \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB PEWNME   2P PYMRH.      ",
	"\tJ03DPABLEHNR!   \nBF C06PALN BCE QM6LEMF!!!        \nH0BAR CTADNR D0CTYJHA.",

	/* Hero story scene select */

	"HA4AL0       ",
	"BX0D K0CTRGKN ",
	"CJACEHNE 3BYK.",
	"TUPEM.0CTP0B \n6EWATS",
	"0TJ0P   \nC TEHRMN   ",
	"Z0PA JPNBEDEH.",
	"MNP0B.Z0CJ0DCTB0",
	"B0DHAR MNHA ",
	"ZDE QZMQH?     ",
	"QZMQH...\nCKPFT.6A3A ",
	"K0CM0 CTAPT      ",
	"K0CM0K0L0HNR\n\"APK\"",
	"J0CL.4ACTS    \nEMEPALSDA     ",
	"C0HNK B TPEB0ZE ",
	"J0CL. GAHC ",

	/* Dark story scene select */

	"HA4AL0       ",
	"BB0D PYMRH ",
	"CKPFT.6A3A \nCH0BA!",
	"TEHS J0CLED. ",
	"0TONLSTP0B\nCKPFT.6A3A ",
	"C06NPAHNE\nTEMHFX     ",
	"D0C\nXA0C N3YMPYD ",
	"0TJ0P   \nC C0HNK0M ",
	"QZMQH     \nNMJEPN",
	"J0CL\nXA0C N3YMPYD ",
	"CKPFT.6A3A \nJEPEXBAT ",
	"0TJ0P   \nC K0CTRGKAMN ",
	"JLAH QZMAHA  ",
	"TANHA  \nTEHEN    ",
	"J0CLEDHRR 6NTBA",

	/* Last story scene select */

	"HA4AL0       ",
	"J0CLEDHRR MNCCNR",
	"   \n0CH0BHAR 6NTBA ",
	"HADEWDF       ",

	/* World ranking and network connection stuff (unused) */

	"HAWMN Y DLR 06H0BLEHNR DATF.  ",
	"BPEMR ATAKN MNP0B. PAHZA ",
	"04KN ATAKN MNP0B0Z0 PAHZA ",
	"QM6LEMA MNP0B.PAHZA ",
	"06GNN PAHZ   ",
	"J0KA3ATS CTADNN         ",
	"J0KA3ATS CTADNN         ",
	"PEDAKT.K0MMEHTAPNN",
	"\tCETEBAR-PEZNCTPAVNR - HE06X0DNM0\nB0NTN B MNP0B0N PAHZ.   ",
	"\tNCJ0LS30BATS J0CLEDHNN 6PAY3EP\nB CETN.        ",
	"\tC0EDNHEHNE C NHTEPHET      ",
	"\tD0 T0Z0 KAK BF B0NDETE B CETS, \nHAD0   3AJLATNTS    TELEO0HHFN \nZ0H0PAP ISP CBR3N.          \nECLN BF NCJ0LS3YETE  ISAO Net \nC TELEO0HA HA4NHAUGEZ0CR C 0990,   \nTELEO0HHAR JLATA 6YDET 10 NEH 3A    \nTPN MNHYTF B C00TBETCTBNN C       \nDNAL          Q2 CNCTEM0N\nJPNGLNTE PYK0B0DCTB0  \nDLR 60LSGEN NHO0PMAV.",
	"\tC0EDNHNTSCR?           ",
	"\t<DA ><HE>",
	"\tC0EDNHEHNE C NHTEPHET N   ",
	"\tD0 T0Z0 KAK BF B0NDETE B CETS, \nHAD0   3AJLATNTS    TELEO0HHFN \nNCJ CBR3S                  \nC0EDNHNTSCR?           ",
	"\t<DA ><HE>",
	"\tHA60P   ||",
	"\t<0TMEHA>",
	"\tBBEDN \"NCJ\" NMR N JAP0LS   ",
	"ID<++>",
	"JAP0LS  <++>",
	"\tHE M0ZY HANTN M0DEM. ",
	"\tJP0BEPKA C0EDNHEHNR.   ",
	"\tLNHNR 3AHRTA     ",
	"\tHA60P CLEDYGEZ0 H0MEPA.   ",
	"\tLNHNR 3AHRTA     ",
	"\tJ0JP06YNTE J03WE.      ",
	"\tLNHNR 3AHRTA     ",
	"\tJP0BEPKA YCTAH0B0K   ",
	"\tHEB03M0WH0     ",
	"\tJP0BEPKA M0DYLSH0N CBR3N, NLN  \nYCTAH0B0K M0DEMA  ",
	"\tHELS3R C0EDEHNTSCR. LNHNR 3AHRTA.   \nJP0BEPS HACTP0NKN M0DEMA N      \nJ0JP06YN J03WE.      ",
	"\tHEB03M0WH0 C0EDNHNTSCR       \nCEPBEP BEPHYL 0GN6KY.        ",
	"\tJP0BEPS NMR N JAP0LS  ",
	"\t0TC0EDNHRTS J0KA HE AKTNBHFN    ",
	"\tJ0KA C0EDNHRETCR, Y TE6R 3AHRT TELEO0H                         \n    \nC0EDNHNTSCR?           ",
	"\tC0EDNHEHNE C C0HNK-CETSU           ",
	"\tCEPBEP 3AHRT       ",
	"\tJ0JP06YN J0DC0EDNHNTSCR J03WE     ",
	"\t06H0BN 6A3Y DAHHFX     \nQT0 M0WET 3AHRTS HECK0LSK0 MNH",
	"<0TMEHA>",
	"\t0TMEHNTS C0EDNHEHNE?   ",
	"<DA ><HE>",
	"\tYBEPEHF 4T0 X0TNTE 0TC0EDNHNTSCR?   ",
	"<DA ><HE>",
	"\tPAHZ YBELN4EH D0 H0MEPA   \n06GEZ0 <++> PAHZA.           ",
	"\tBAG PAHZ 6FL YMEHSGEH     \n06GEZ0 <++> PAHZA.           ",
	"\tBAG PAHZ 6FL YBELN4EH        \n06GEZ0 <++> B  <++> 04KN ATAKN   ",
	"\tBAG PAHZ 6FL YBELN4EH        \n06GEZ0 <++> B  <++> BPEMR ATAKN ",
	"\tPAHZ YBELN4EH D0 H0MEPA   \n06GEZ0 <++> QM6LEMF PAHZA.    ",
	"\tBAG PAHZ 6FL YMEHSGEH        \n06GEZ0 <++> B  <++> 04KN ATAKN   ",
	"\tBAG PAHZ 6FL YMEHSGEH        \n06GEZ0 <++> B  <++> BPEMR ATAKN ",
	"\tBAG PAHZ 6FL YMEHSGEH     \n06GEZ0 <++> QM6LEMF PAHZA.    ",
	"<++>",
	"\tNCJ0LS30BATS T0T E-MAIL\nDLR J0DTBEPWDEHNR\n(M0WH0 YCTAH0BNTS E-MAIL   \nHA 0TJPABKY J03WE.       )",
	"<DA ><HE>",
	"\tHE E-mail YCTAH0BKA HA DPNMKQCT",
	"\tNCJ.H0BENGNN 6PAY3EP DLR    \nHACTP0EK E-MAIL",
	"TF BBEL <++>?",
	"\tJAP0LS.             ",
	"\t<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\tJAP0LS HEBEPHFN.            \nBBEDNTE JAP0LS CH0BA.",
	"<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\t0T0CLATS BAM JAP0LS HA\nHA                E-mail?",
	"<DA ><HE>",
	"\t6YDET 0TJPABLEH0\nHA BAG E-MAIL ADPEC. \nJP0BEPSTE J04TY.       ",
	"\tD06P0 J0WAL0BATS B CETS-C0HNK",
	"\tBBEDNTE NMR.         ",
	"\t12 CNMB0L0B MAKCNMYM \nDLNHF DLR NMEHN.     ",
	"<BB0D > <0TMEHA>",
	"<++>",
	"\tTAK0E NMR YWE CYGECTBYET.",
	"\tBBEDNTE JAP0LS ECLN  \nX0TNTE NCJ0LS30BATS QT0 NMR",
	"<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\tDALEE, BB0D JAP0LR.  ",
	"\tMNHNMALSHAR DLNHA JAP0LR 5  \nCNMB0L0B, MAKCNMYM - 12.  ",
	"<BB0D ><BEPH>",
	"\tBBEDNTE    E-MAIL  ",
	"\tECLN BF 3A6YDETE JAP0LS, T0  \n0H M0WET 6FTS BFCLAH J0 E-MAILY.   ",
	"<BB0D ><0TMEHA>",
	"\tX0TNTE DELNTS BAG E-MAIL C      \nDPYZNMN J0LS30BATELRMN?  \nECLN HET, BF6EPNTE \"HET\". ",
	"<DA ><HE>",
	"\tBF6EPNTE CTPAHY N PAN0H\nZDE BF WNBETE. ",
	"CTPAHA: <++>",
	"PAN0H<++>",
	"<BB0D ><0TMEHA>",
	"\tCETS C0HNK MECT0 ZDE M0WH0 06MEHRTSCR\nNHO0PMAVNEN C DPYZNMN J0LS30BATELRMN \nJ0 BCEMY MNPY.  J0WALYNCTA,    \nBEDNTE CE6R VNBNLN30BAHH0.         \nJPEDYJPEWDEHNR M0ZYT NCX0DNTS 0T   \nJ0LS30BATELR, 0HN MYZYT HE     \nNCJ0LS30BATS HAG CEPBEP ECLN 3DECS\n6YDYT WECT0KNE JPABNLA.    ",
	"",
	"<++>'s ",
	"PEZNCTPAVNR 3ABEPGEHA.",
	"\tJ0KA3ATS PAHZN C BEPXY.      ",
	"\t0C06FE PAHZN.          ",
	"\tNCKATS PAHZ J0 NMEHN.       ",
	"\tCJNC0K CTPAH NLN PAN0H0B.       ",
	"\tBBEDNTE PACCTAH0BKY           ",
	"<++>",
	"\tBBENDE NMR K0T0P0E HAD0 HANTN.     ",
	"<++>",
	"\tBBEDNTE CTPAHY                 ",
	"CTPAHA <++>",
	"PANH<++>",
	"<BB0D ><0TMEHA>",
	"\tNHO0PMAVNR J0LS30BATELR      ",
	"\tHAWMN B DLR T0Z0    \n4T0SF BEPHYTSCR     ",

	/* Hero story recaps */

	//City Escape
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"HEK0T0PFE B0NCKA 6FLN 06HAPYWEHF    \nN 0HN CKA3ALN 4T0 NCKALN MEHR.     \nJ0X0WE 0HN M0ZYT B3RTS MEHR    \nHA JP0ZYLKY KYDA-HN6YDS!",
	"QN!4T0 QT0? DNK006PA3?      \nJ0D0WDN-KA!!  \n0 4EM TF Z0B0PNGS?         \nR HE DE3EPTNP N3       \nB0EHHFX CNL!          ",
	"R DYMAL 4T0 QT0 KAKAR-T0     \nGYTKA, H0 QT0 HE CMEGH0!      ",
	"R C06NPAUCS YNTN 0T CUDA",

	//Big Foot
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"4T0 3A CBR3KA TRWELFX  \nZ0L0BEGEK! H0 KT0 0HN B    \nDENCTBNTELSH0CTN?        ",
	"0HN HE T0LSK0 0X0TRTCR 3A   \nMH0N DHEM N H04SU, H0 0HN  \nB3RLN B ZP0MADH0M P060TE  \n4T06 J0NMATS. ",
	"DYMAU 0HN JPABDA PEGNLN           \n3A6PATS MEHR!       ",
	"H0 0HN 4T0 JPABDA BEPRT 4T0 QT0   \nCPA60TAET? R J0KAWY NM K0E-  \n4T0......T0LSK0 DAN MHE TPN   \nMNHYTF C0EDNHNTSCR!          ",

	//Wild Canyon
	"R K0CTRGKN NGNHDF.       \nH0 M0WEGS 3BATS MEHR K0CTRGKN",
	"0DHAWDF, MACTEP N3YMPYD  6FL  \nYKPADEH C 0CTP0BA AHZEL0B.   ",
	"B0P 0KA3ALCR BCE3HANK0N  \nDEB04K0N LETY4EN MFGSU   \nN3 BCEX BEGEN.",
	"K0ZDA QTA DEB04KA MEHR HACTNZHET\nKT0 KAK TF DYMAEGS 06HAPYWNTCR?  \nDA, JPABNLSH0, QZMAH!     \n0H JPNGEL B0 BPEMR 0ZPA6LEHNR\nM0N JLAH N J0JFTATSCR B3RTS   \nMACTEPA N3YMPYDA!  ",
	"R PEGNL PA36NTS       \nMACTEP N3YMPYD HA KYCKN   \nD0 T0Z0 KAK QZMAH PEGNL \n6EWATS. CEN4AC R D0LWEH NX\nHANTN.     ",
	"QTA DEB40HKA LETY4AR  \nMFGS T0WE.         \nMHE HAD0 C06PATS NX N J0L0WNTS    \nN3YMPYD HA3AD 04EHS 6FCTP0!       ",

	//Eggman 1
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R CM0TPEL TB N YCLFGAL    \nH0B0CTN.                   \nR 6FL G0KNP0BAH YBN-\nDEB C0HNKA. ",
	"C0HNK APECT0BAH 3A 4T0\nT0 DENCTBNTELSH0 YWACH0E, \n4T0 HE J0X0WE HA C0HNKA.",
	"R HE M0Z J0BEPNTS 4T0 QT0 TAK, \nJ0QT0MY AW J0DJPFZHYL N      \nJ0JAL JPRM0 HA TUPEMHFN\n0CTP0B.       ",
	"YZADAN KAK?              \nQZMAH! 0H CH0BA C0 CB0NMN  \n3L06HFMN GTY4KAMN!       \nQT0 HE X0P0G0!     ",
	"OK, BPEMR BFPBATS H0BFN  \nT0PHAD0 N CJACTN QMN!    ",
	"JPEBPAGEHNE T0PHAD0!   ",

	//Prison Lane
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R M0Z 6F CJACTN QMN 0T QZMAHA, H0  \n0HA CKA3ALA, 4T0 QZMAH CH0BA C0  \nCB0NMN 3LFMN D0P0ZAMN, JLAHNPYET\n4T0-T0 DENCTBNTELSH0 60LSG0E!  ",
	"HAD0 CLEDNTS 3A QZMAH0M, H0    \nCHA4ALA HAD0 CJACTN KP0GKY,     \nC0HNK!",
	"4T0 QT0?    \nTF X04EGS T0WE?    \nHY, ECLN TF JPABDA X04EGS,\nT0 R HE JP0TNB. \nH0 HE CT0N HA M0EM JYTN! ",

	//Metal Harbor
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"4T0 B QT0M MNPE     \nAMN DELAET 3DEC",
	"HE HAGE DEL0.....HAD0 HANTN QTZ0   \n4EPH0Z0 DNK006PA3A, K0T0PFN    \nJ0X0W HA M0U TEHS! 0H ZDE-\nT0 HA 0CTP0BE,           \nR 3HAU QT0",
	"R TPA4Y 3DECS CB0E BPEMR!\nR 06MAHY 0XPAHY N YDAP        \nD0LWEH 6FTS J0 CTFKY!     ",
	"T0 ECTS R CEN4AC   \nDE3EPTNP?          ",

	//Shadow 1
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"J06EZ N3 TUPSMF -  \nHET JP06LEM!   \nN R T0WE HAGEL TEHS!       ",
	"0H HE Y6EWNT HA QT0T PA3!    ",

	//Green Forest
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"R J04TN HAGEL TEHS \nH0 R T0P0JNLCR.       \nLY4GE DENCTB0BATS N 6FCTP0\n\nQZMAH CKA3AL 4T0      \nYCTAH0BNL CBR3S MEHEE \n4EM 3A JRTS MNHYT!        ",
	"QZMAH CKA3AL 4T0      \nYCTAH0BNL CBR3S MEHEE \n4EM 3A JRTS MNHYT!        ", //unused
	"R D0LWEH EXATS HA QT0T\n0CTP0B N 6FCTP0! \nZDE QMN N XB0CT!       ",

	//Pumpkin Hill
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"CLEDYR CLA60MY CNZHALY  \nJ0LY4EHH0MY 0T MACTEPA\nN3YMPYDA, R HAGEL      \nCE6R B QT0M CELSCK0M KAHS0HE",
	"04EHS ZADK0, H0 R HE \n60UCS JPNBNDEHNN!        ",
	"R D0LWEH HANTN KYCKN     \nN3YMPYDA HEMEDLEHH0!      ",

	//Mission Street
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"QZMAH 06SRBNL CB0N   \n3L0N JLAH Z0CJ0DCTBA  \nHAD BCEM MNP0M!",
	"0H JP0CT0B30PBAL J0L LYHF    \nQTNM M0GHFM 0PYWNEM N    \nTEJEPS ZP03NTSCR 3AXBATNTS \nBCU JLAHETY!         \nR YBEPEH, 4T0 QT0Z0 HE CLY4NTCR! ",
	"QZMAH J0DKLU4AETCR K     \nQHEPZNN XA0CA N3YMPYDA DLR  \nYBELN4EHNR M0GH0CTN.  ",
	"TEJEPS QT0 3A MH0N\nR HANDY QZMAHA N    \nXA0C N3YMPYD0B!    ",
	"CHA4ALA HAD0 HANTN   \nHADEWH0E MECT0!      ",

	//Aquatic Mine
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"CLEDYR 3A CNZHAL0M  \n0T MACTEPA N3YMPYDA, R  \nHAGEL CB0N ZLY6NHF BHYTPN \nQT0Z0 KAHS0H",
	"QT0 MECT0 J0X0WE HA  \nJYCTFHU NLN BP0DE T0Z0.      \n60LSGAR 4ACTS J0D B0D0N!    ",
	"HYWH0 HANTN KYCKN             \nMACTEPA          \nN3YMPYDA 3DECS.     \nHET BPEMEHN QT0 06CYWDATS!   ",
	"HAD0 HANTN QTN KYCKN        \nKAK M0WH0 6FCTPEE!         ",

	//Route 101
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R CLED0BAL 3A       \nCNZHAL0M 0T XA0CA N3YM-\nPYDA QZMAHA.       ",
	"4T0 QZMAH 6YDET    \nDELATS B K0CM0C",
	"HE 6ECJ0K0NCR\nR HANDY T04H0E PACJ0L0WEH-\nNE QZMAHA N 04EHS CK0P0!     ",
	"HE JEPEWNBAN,QMN\nJ0MHN, R \"L0BKA4\" K0ZDA   \nJPNX0DRT MEXAHN4ECKNE BEGN!    ",
	"R HANDY JPE3NDEHTA!     ",

	//Hidden Base
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"MF EXALN B JPE3NDEHTCK0M  \nLNM0 N YZADAN 4T0?  \nMF HAGLN ZDE QZMAH   \nJPR4ETCR! ",
	"QZMAH N EZ0 JPNRTELN  \nB K0CMN4ECK0N K0L0HNN, APK.  ",
	"CLEDYUGNN GAZ - HANTN CEKPET-\nHYU 6A3Y QZMAHA,    \nZDE-T0 B JYCTFHE!       ",
	"DABAN! R J0NDY JEPBFN N  \nHANDY BX0D.       ",

	//Pyramid Cave
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"MF PEGNLN JP6PATS- \nCR B JNPAMNDY N HANTN    \n6A3Y QZMAHA!         ",
	"ECTS D0P0ZA 4T06F         \nJ0JACTS B K0CM0C 0TCUDA.     \nY HAC HET BPEMEHN,      \nJ0GLN!   ",

	//Death Chamber
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"MF CM0ZLN 06HAPYWNTS  \nCEKPETHYU 6A3Y QZMAHA\nB ZLY6NHE JNPAMNDF.     ",
	"TEJEPS HAM HAD0    \nHANTN KLU4 0T DBEPN,     \n4T06F J0JACTS TYDA.      ",
	"4T0? J04EMY R D0LWEH  \nNCKATS QT0T KLU4? QT0 HE M0R PA- \n60TA, H0 R CDELAU.\nR D0LWEH J0T0MY 4T0   \nQT0 DLR MACTEPA N3YMPYD",
	"R J0KAWY TE6E YMEHNR    \nK0T0PFE DELAUT  \nMEHR VEHHFM 0X0THNK0M!   ",

	//King Boom Boo
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"QT0 LAK0MFN KYC04EK!     \nR HAGEL KLU4 N TEJEPS  \nBPEMR N3Y4NTS CEKPETHYU 6A3Y \nQZMAHA.     ",
	"4T0 QT0 6FL0? \nY MEHR JL0X0E JPED4YBCTBNE!       \nKAK 3DECS MEP3K0. 3DECS M0ZLN   \n6FTS DYGN TEX CTPAWEN M0ZNL?    ",
	"HE DYMAU R M0ZY D0Z0B0- \nPNTSCR...H0 T0ZDA KAK   \nR HANDY KYCKN         \nN3YMPYDA?             \n4EPT, Y MEHR HET BF60PA",

	//Egg Golem (hero)
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"CJACN60 K0CTRGKAM, \nMF CM0ZLN 0TKPFTS DBEPS   \nK CEKPETH0N 6A3E QZMAHA.     ",
	"HEN3BECTH0 0TKYDA  0H\nJ0RBNLCR N ZP0MADHAR CTA- \nTYR 0WNLA! ",
	"4EPT0BA EZ0 Z0L0BA\nKAK 0H Y3HAL   \n4T0 MF JPNDEM? ",
	"TF JPADA DYMAEGS 4T0 KY-\nC0K KAMHR M0WET 0CTAH0BNTS",

	//Eternal Engine
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"MF JP0BELN T0K        \n0T CEKPETH0N 6A3F QZMAHA N     \nHAK0HEV-T0 JPN6FLN B K0CMN4EC- \nKYU K0L0HNU, APK.        ",
	"M0R NDER-YHN4T0WNTS 0PY- \nWNE NCJ0LS3YUGEE     \nJ0DDELSHFN N3YMPYD! ",
	"NHTEPECH0, C0HNK \nJ0NMET JLAH?         ",
	"HANTN CNLY               \nN KAK M0WH0 CK0PEE!   ",

	//Meteor Herd
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"KYCKN MACTEPA    \nN3YMPYDA MH0N C06PAHHFE,  \nTEJEPS JLABAUT B K0CM0CE. \nHAM CLED0BAL0 6F      \n0XPAHRTS NX       \nLY4GE!            ",
	"QT0 HE LEZKAR PA60TA\n3AGNTA MACTEPA N3YMPY\nDA, TF 3HAEGS QT0?",
	"R D0LWEH HANTN NX D0 T0Z0 \nKAK MF NX J0TEPREM.",

	//Rouge
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"J0CLE HAX0WDEHNR J0L0BNHF\nKYCK0B MACTEPA N3YMPYD0B, R  \nJPNDY K T0N DEB40HKE, CH0BA!    ",
	"YBEPEH, Y HEE DPYZAR   \nJ0L0BNHA.          \nHET BPEMEHN 60LTATS!   \nR HE DAM EN HN GAHCA!       ",
	"R BEPHYL TE KYCKN    \n06PATH0!    ",

	//Crazy Gadget
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"HAG JLAH C0BEPGEHEH, \nJ0KA 0H  DEPWNT QMN!      ",
	"QZMAH CKA3AL 4T0 J0MEHRET \nQMN HA N3YMPYD........\nR YWE DYMAL 06 QT0M!           ",
	"HE BPEMR GYTNTS!          \nQZMAH Z0T0B CH0BA     \nNCJ0LS30BATS 0PYW!",
	"XB0CTF,QMN, DEPWNCS\nR NDY!     ",

	//Eggman 2
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"C0HNK 3AXBA4EH N      \nYJAK0BAH B KAJCYLY. QZMAH  \nBFCTPELNT KAJCYLY B K0CM0C \nN B30PBET EE!   ",
	"HET, QT0 HE JPABDA!  \nC0HNK HE YMPET!     ",
	"QZMAH! R HE J03B0LU    \nYNTN C QTNM!       \nR 06EGAL C0HNKY 4T0 HE     \n6P0GY N R HE 6P0GY. \nTF 3AJLATNGS 3A QT0!       ",

	//Final Rush
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"R NCJ0LS3YU    \nXA0C K0HTP0LS, N    \nYDEPY N3 L0BYGKN     \nQZMAHA!            ",
	"Y HAC HE TAK MH0Z0 BPEMEHN\nD0 T0Z0 KAK 0PYWNE 3ADENCTB. !",
	"R NCJ0LS3YU GAHC N  \n6P0GY QT0T N3YMPYD B JYGKY \nD0 T0Z0 KAK 0HA BFCTPELNT!!",

	//Shadow 2
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"K00PDNHAVNR HE JL0XA!    \nJP0CT0 K0ZDA R DYMAL BCE \n6FL0 J0D K0HTP0LEM, TEHN \nJ0RBNLNCS.       \nHAD0 3AK0H4NTS CPAWEHNE  \nJP0TNB 4EPH0Z0 DNK006PA3A,CEN4AC!",
	"J0KAWNTE 4T0 M0WETE, TEHN!   \nPEALSHAR M0GS....KLACC!!",

	/* Dark story recaps */

	//Iron Gate
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"CLY4ANH0, R \nHAGEL DHEBHNK DEDYGKN.         \nB HEM, 0H 0JNCAL MNCTN4ECKNN    \nCEKPET 0PYWNE K0T0P0Z0  \n0H HA3FBAL \"JP0EKT TEHS\".          ",
	"DHEBHNK J0X0WE 6FL 3AKPFT BHYTPN   \nB0EHH0-NCCLED0BATELSCK0M VEHTPE K0ZDA\n0H 6FL 3AKPFT.       \n50 LET HA3AD.     ",
	"6ECJ0LE3H0E NCCLED0BAHNE!     ",
	"HACLEDNE BELN4ANGEZ0 Y4EH0Z0 M03ZA   \nB NCT0PNN MNPA, JP0OECC0P        \nZEPALSD. QT0 M0N DEDYGKA!!!         ",
	"R D0LWEH B0CJ0LS30-\nBATSCR QTNM!       ",

	//Hot Shot
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"PA36YWEH N3 ZLY60K0Z0   \nCHA, DLNBGEZ0CR 50 LET.   ",
	"D0KT0P QZMAH, \nBHYK M0EZ0 C03DATELR, JP0O.\nZEPALSD 0CB060DNL MEHR.       ",
	"D0KT0P PA36YDNL MEHR  \nN J0QT0MY, R BFJ0LHNL EZ0   \nJP0CS6Y.   ",
	"CHA4ALA, R J0KAWY CNLY\nK0T0P0N R BLADEU.    \n3A 10 CEKYHD R M0Z       \nYHN4T0WNTS B0EHH0E CHAPRWEHNE   \nKAK NZPYGKY!      ",

	//Dry Lagoon
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R JP0CT0 LU6LU DPAZ0VEHH0CTN N\nHE BNWY D0CTAT04H0Z0 K0L-BA\nR HAGEL 04EHS VEHHFN      \nMACTEP N3YMPYD H0....",
	"QT0 CLEDYET          \n3A MH0N.              \n0H TAK HACT04NB!   ",
	"KP0ME T0Z0 QT0T CTPAHHFN MYW- \n4NHA CTPAHH0 CM0TPRGNN HA YCF \n3A6PAL  EZ0 Y MEHR, H0 D0  \nT0Z0 KAK QT0 CLY4NL0CS,  \n0H PALETELCR HA KYC04KN.     ",
	"0X, 4T0 TF HADELAL!       ",
	"TEJEPS R D0LWEH HANTN N\nC06PATS BCE KYCKN BMECTE!!",

	//Sand Ocean
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R N36ABNL TEHS 0T     \nB0EHH0Z0 CPEDCTBA H0          \nTEJEPS....",
	"TEHS CKA3ALA B3RTS     \nN3YMPYD XA0CA N BEPHYTS   \nEZ0 B K0CM0K0L0HNU, APK.     ",
	"D0LWH0 6FTS 4T0-T0 JP0NCX0DNT.   \nMHE CLEDYET BEPHYTSCR K 6A3E\nN JP0BEPNTS QT0!!",

	//Radical Highway
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"R 3A6PAL N3YMPYD XA0CA N3    \nHAVN0HALSH0Z0 PE3EPB.6AHKA",
	"N TEJEPS B0EHHFE N J0LN-\nVNR 0X0TRTCR 3A MH0N. \nMHE HAJLEBATS ECLN 0HN 3HAUT KT0 R\nTAK KAK HNK0ZDA HE J0NMAUT MEHR\nR JP0CT0 J0TEPRL BPEMR!   ",
	"HET BPEMEHN B NZPF NZPATS.\nR D0LWEH Y6PATSCR 0TCUDA, 6FCTP0",

	//Egg Quarters
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R CM0Z J0L0WNTS TPAHCMNTTEP B  \nTY MAGNHY CTAP0Z0 MYW4NHF\nK0ZDA 0H BJEPBFE JPNGEL",
	"HE M0ZY CKA3ATS J04EMY...J0KA.  ",
	"J0T0M R JP0CLEDNL 3A HNM D0\nQT0N JNPAMNDF, H0 HE\nCM0Z B0NTN, J0T0MY 4T0     \nDBEPS 6FLA 3AKPFTA. ",
	"XMM, M0WET HAD0 HANTN    \nKLU4 NLN 4T0-T0 J0D06H0E.    ",

	//Lost Colony
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R J0GEL B K0CM0K0L0HNU, APK,KAK\nCKA3ALA MHE TEHS.       ",
	"4T0 B VEHTPALSH0M J0MEGEHNN  \nAPK?            \nHAD0 BFRCHNTS QT0! ",

	//Weapons Bed
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"DEB40HKA, P0DW,     \nC0EDNHNLA  HAGY CNLY \nN MF BEPHYLNCS B TUPEMH.0CTP0B",
	"MF 3DECS 4T06F HANTN  \nN3YMPYD XA0CA,    \nK0T0PFN XPAHNTCR ZDE-T0 \nB B0EHH0-NCCLED0BATELSCK0M VEHTPE.",
	"R J0NDY JEPBFM N     \n0TBLEKY C0LDAT.     \nXA...T0ZDA MF 3ABEPGNM HAGA JLAHF!    ",

	//Tails 1
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"K0ZDA MF 6YDEM TAM \n4T06F D0CTATS N3YMPYD     \nXA0CA, KT0-T0 TAM 6YDET  \n4T06F 0CTAH0BNTS HAC!        ",
	"TEHS, P0DW, BJEPED!    \nR J03A604YCS 0 HEM!    ",
	"Y6NTS TE6R - DLR MEHR \nYD0B0LSCTBNE!     ",

	//Security Hall
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R BHYTPN        \nB0EHH0-NCCLED0BATELSCK0Z0, \nD0KT0P JLAHNP0BAL QT0.        ",
	"HAD0 HANTN TPN          \n0CTABGNXCR N3YMPYDA XA0CA\nQT0 D0LWH0 6FTS KYC04EK!       ",

	//Flying Dog
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"MALFN HA60P.     \nKAK R M0Z J03B0LNTS  \nCLY4NTSCR QT0MY C0 MH0N",
	"J0CLE C06PAHNR TPEX \nN3YMPYD0B XA0CA, 4T0-\nT0 J0JAL0 B M0N ZLA3A!  \nTAK BHE3AJH0......",
	"CNZHALN3AVNR 0TKLU4EHA N R \n6FL J0NMAH B            \nL0BYGKY! ",
	"N3 HN0TKYDA JPNGEL  \nQT0T C BNDY CNLSHFN 60EV.         \nY HAC HE TAK MH0Z0 BPEMEHN\nD0 T0Z0 KAK 60M6A          \nCPAS60TALA!  \n0X, JP0CT0 QT0 HE M0N DEHS! ",
	"CHA4A-\nLA HAD0 J03A60TNTSCR 0 DELAX.     ",

	//White Jungle
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"J0X0WE TA DEB40HKA     \nJP0NZPALA CB0E DEL0.           ",
	"0HA MHE HE 6E3PA3LN4HA, \nQT0 N3YMPYD XA0CA,       \nK0T0PFN HAD0 C0XPAHNTS. ",
	"HAD0 CJEGNTS J0T0MY 4T0 HE TAK \nMH0Z0 BPEMEHN 0CTAL0CS D0\nT0Z0 KAK 60M6A 6AX",

	//Sonic 1
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"J0RBNLNCS DPYZNE DNK006PA3F \nJ0KA R 6FL HA JYTN K \nCJACEHNU P0DWA. ",
	"0H HA4NHAET PA3DPAWATS MEHR. \nBPEMR J0KA3ATS PEALSHYU CNLY!   ",

	//Route 280
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"MF 06SRBNLN HAG JLAH MNP0-\nB0Z0 Z0CJ0DCTBA NCJ0LS3YR \nCNLY N3YMPYD0B XA0CA YKPA- \nDEHHFX HAMN NX B0EHH0-NCC-\nLED0BATELSCK0Z0.  ",
	"3APRWATS JYGKY 3ATMEHNR    \n04EHS D0LZ0!       ",
	"J0QT0MY HAD0 D0CTATS   \nJ0CLEDHNN N3YMPYD 6FCTP0!   \nZDE QT0T B0PNGKA?     ",

	//Sky Rail
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"R J0CLAL C006GEHNE P0DWY \n4T06 0H CLED0BAL QT0MY JLAHY.\nY JNL0TA ECTS J0CLEDHNN   \nN3YMPYD XA0CA.            ",
	"3DECS TAK MH0Z0 BF3FBAU-\nGNX CTPAX Z0P BJEPEDN MEHR......\nJYCTRKN, R HE   \nJ03B0LU CAM0LETY YLETETS!      ",

	//Egg Golem (dark)
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R WDY C0HNKA HA M0EN TANH0N  \n6A3E, 4T06F J0KA3ATS EMY  \nP060TA C03DAHH0Z0 DLR       \nYCTPAGEHNR, H0.................",
	"QT0T Z0LY6.DNK006PA3 CH0BA CCFLAETCR\nCEN4AC EZ0 ATAKYUT N 0H   \nJPNDET K0 MHE J0CLE\n4T0 3DECS BE4H0 JP0NCX0DNT? ",
	"XEN, JP04S C D0P0ZN!   \nC0HNK 6EWAL!     ",

	//Mad Space
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"H0 QT0 HE BCE 4T0 R ......",
	"NTAK, TE JAPHN J0RBNLNCS    \nK0ZDA R BEPHYLCR N3    \nCEKPETH0N MNCNN",
	"QT0 3HA4NT 4T0 0HN C06PALN      \n0CTALSHFE KYCKN MACTEPA       \nN3YMPYDA. QT0 M0N GAHC!   ",
	"R B0CCTAH0BNL NHO0PMAVNU 0 TANH0M   \nJP0EKTE \"TEHS\", TEJEPS QT0   \nM0N GAHC 3AXBATNTS     \nMACTEPA N3YMPYDA N Y6EWATS!!",

	//Knuckles
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"0H HA4NHAET MEHR PA3DP0WATS!      \n0H HEYM0LNM HAC4ET    \nMACTEPA N3YMPYDA, HE TAK LN!?\nJ04EMY 0H JP0CT0 HE 6P0CNT? \nQT0 D0CAWDAET.        ",
	"R J0KALE4Y EZ0 N B03SMY    \nMACTEPA N3YMPYDA!  ",

	//Cosmic Wall
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"C0HNKA N EZ0 DPYWK0B \nK0ZDA HANDY KAK J0JACTS B \nK0CM0K0L0HNU.       ",
	"J04EMY MHE HAD0 4NTATS N3 DBYX\n4ACTEN N3YMPYD0B XA0CA?     \n4T0 JP0NCX0DNT!!",
	"0HN HABEPH0 JLAHNPYUT\nK0HTPATAKY.      ",
	"Y MEHR HET BPEMEHN!       \nHA3AD B K0CM0K0L0HNU DLR\nYDAPA J0 HNM.  ",

	//Tails 2
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"XAXAXAXAXAXA!\nR CDELAL QT0! R J06EDNL C0HNKA!       \nQT0T DNK006PA3 CEN4AC \nJPNDET HABCEZDA!    \n0H JP0CT0 JLFBY4NN       \nKYC0K B K0CM0CE!    ",
	"4T0 TF 6YDEGS DELATS TEJEPS, TANLC?\nECLN TF JP0TNB MEHR,  \nTF J0CTPADAEGS TAKWE KAK   \nTB0N DPYWKN, C0HNK.  ",

	//Final Chase
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"HAK0HEV-T0 BCE CEMS 4ACTEN N3YMPYDA  \nXA0CA HA MECTE.  \nTEJEPS YCTAH0BLEH0,  \nR J04TN 3AK0H4NL!   ",
	"BCE QT0 BPEMR, KT0-T0 JFTAETCR \nD0CTATS JYGKY 3ATMEHNR.             \nEMY HE4EZ0 DAWE HADERTSCR!  ",
	"BAWH0, 4T06F MF HE D0JYCTNLN\nCEN4AC HNKAK0N 0GN6KN.      \nHAD0 N36ABNTSCR 0T BCEX    \nJAPA3NT0B!  ",

	//Sonic 2
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"QT0 T0T Z0LY60N DNK06PA3 K0T0PFN JF- \nTALCR YHN4T0WNTS HAGY JYGKY!  ",
	"R J0PAWEH.    \nR DYMAL 0H YMEP B KAJCYLE K0T0- \nPYU MF BF6P0CNLN B K0CM0C",
	"TEJEPS R 3HAU 4T0 0H 04EHS    \n0JACEH!      ",
	"K0ZDA R C HNM PA36EPYCS, 0H 6YDET\nWALETS 4T0 HE YMEP B T0N KAJCYLE.  \nR J0KAWY EMY M0U PEALSHYU CNLY.  ",

	/* Last story recaps */

	//Cannon's Core
	"MEHR 30BYT QMN P03A.\nR YMEH N J0L0H QHEPZNN!     ",
	"JP0N30NDET HE4T0 YWACH0E!       \nJP0OECC0P ZEPALSD AKTNBNP0BAL  \nQTY JP0ZPAMMY YWE DABH0.",
	"JPN4NH0N AKTNBAVNN QT0N    \nJP0ZPAMMF 6FLA CC0PA B K0L0HNN \nHA EZ0 0P6NTE. TEJEPS, KPAX 6YDET N HA\n3EMLE!                ",
	"J0X0WE QZMAH 06MAHYL \nTEHS.          ",
	"0H 3L0N D0KT0P!          \nR X04Y KPNKHYTS HA HEZ0,H0 CHA4A\nLA HAD0 0CTAH0BNTS K0CM0K0L0HNU \n0T J0PAWEHNR.",
	"MF PEGNLN 06SEDNHNTS \nN J0NTN B RDP0 K0L0HNN 4T06   \n0CTAH0BNTS CNLY N3YMPYD0B XA0CA.    ",
	"Y HAC 0CTAL0CS MAL0 BPEMEHN!!\nDEPWNTECS........BJEPED!        ",

	//The Biolizard
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"CJACN60 QMN, R CM0Z 3AJ0M\nHNTS WELAHNE MAPNN.      ",
	"K0ZDA R HAK0HEV-T0 0303HAL \nQT0 JP0T0TNJ WN3HN JFTALCR \n0CTAH0BNTS MEHR. ",
	"R J03A604YCS 06 QT0M, C0HNK!    \nJ0CTAPANCR 0CTAH0BNTS CNLY     \nN3YMPYD0B XA0CA.   ",

	//The Finalhazard
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"MF CM0ZLN 0CTAH0BNTS CNLY        \nN3YMPYD0B XA0CA, H0       \nK0CM0K0L0HNR BCE EGE JADAET.  ",
	"QT0T JP0T0TNJ CTAL 0DNH C    \nK0CM0K0L0HNEN N BEDET EE K          \nCT0LKH0BEHNU C 3EMLEN.              ",
	"K0CM0K0L0HNR B0NDET B  3EMHYU    \nATM0COEPY 04EHS CK0P0.      \nHAD0 YHN4T0WNTS EE CEN4AC!",
	"CNLA 3AJPABLEHA KAK         \nJ0WELALN. J03B0LS MHE     \nJ0KA3ATS CYJEP CNLY C0HNKA!"
};

std::vector<const char*> PauseMenuKudos
{
	/* Pause menu */

	"\aDALEE   ",
	"\a3AH0B0 ",
	"",
	"",
	"",
	"\aYX0D"
};

#pragma endregion

#pragma region Vector

std::vector<const char*> AdvertiseVector
{
	/* Main menu */

	"\t0DNH04HSN PEWNM   ",
	"\tPEWNM UP0TNB  ",
	"\tU0KA3 TA6VNQS PEK0PD0B.              ",
	"",
	"",
	"",
	"\aYNTN",

	/* Help & options */

	"\tJKCTPA MEHG",
	"",
	"",
	"",
	"\tCMEHA 0UQNN   ",
	"",

	/* Single player */

	"\tNLPA U0 NCT0PNN.          ",
	"\tBS60P CQEHS N3 NCT0PNN.     ",
	"\tUP0NDEHHSE JTAUS.           ",

	/* Some 2P mode stuff */

	"\tTPN TNUA NLPS.             ",
	"\tJT0 NLPA HA KAPTAX.          ",
	"\tXA0 L0HKN U0DHRVNCF HA (8) XA0.   ",

	/* Extras */

	"\tU0KA3 TA6VNQS PEK0PD0B.              ",	//world ranking
	"\t06RCHEHNE NLPS.               ",			//tutorial
	"\tC06PAHHSE JM6VEMMS.                   ", //emblem results
	"\tU0DLPYWEHHAR NLPA.     ",				//DLC

	/* Memory card select (console leftover) */

	"\tBS60P KAPTS UAMRTN.  ",
	"\tHET 6V0K0B DVR 3AUNCN.          ",

	/* File select */

	"\tBS60P OANVA.  ",
	"\tC03DATF OANV.     ",
	"\t3ALPY3NTF.  ",
	"\tX04EZF YDAVNTF JT0T OANV?       ",
	"\tHET MECTA DVR 3AUNCN XA0.          ",

	/* Options */

	"\tO0H0BAR MY3SKA",
	"\tCTEPE0 / M0H0.       ",
	"\t0UQNN BN6P0 UAKA.         ",
	"\tR3SK TEKCTA N 3BYKA.               ",
	"\tCMEHA OANVA.",
	"\tCMEHA CXEMS JKPAHA MEHG. ",
	"\tHACTP0NKN TB.         ",
	"\tCMEHA HA CTEPE0 3BYK.  ",
	"\tCMEHA HA M0H0 3BYK.      ",
	"\tBN6PA BK.    ",
	"\tBN6PA BSK.    ",
	"\tAHLVNNCKNN.       ",
	"\tRU0HCKNN.          ",
	"\tPYCCKNN.         ",
	"\tRU0HCKNN.         ",
	"\tHEMEQKNN.       ",
	"\tOPAHQY3KNN.     ",
	"\tNCUAHCKNN.       ",

	/* Sound test general */

	"\tBS60P KATEL0PNN MY3SKN.              ",
	"\tBS60P 3BYKA NVN MY3SKN.             ",

	/* Menu themes */

	"\tHYWH0 3ALPY3NTF OANV CXEMS. ",
	"\tBS60P CXEMS.   ",
	"\t3ALPY3KA CXEMS.    ",
	"\t0ZN6KA 3ALPY3KN CXEMS.    ",
	"\tHET OANV0B CXEMS.      ",
	"\tCKA4ATF OANV C BE6-CANTA.  ",

	/* TV settings */

	"\tTECT TB HA 60LQ.                ",
	"\tKAPTNHKA 6YDET U0KA3AHA HA 5 MNHYT.",
	"\tECVN 0HA K0PEKTHAR, 3HA4NT 60LQ ECTF.",
	"\t50LQ JKPAH.  ",
	"\tKAPTNHKA U0KA3AHA B PEWNME UAV.   ",
	"\t60LQ JKPAH.  ",
	"\t60LQ C0BMECTNM0CTF HYWHA.   ",

	/* Separate string for Italian language */

	"",

	/* Progression percentage (unused) */

	"H0B",
	"10%3ABEP",
	"20%3ABEP",
	"30%3ABEP",
	"40%3ABEP",
	"50%3ABEP",
	"60%3ABEP",
	"70%3ABEP",
	"80%3ABEP",
	"90%3ABEP",

	/* Story select */

	"\tBS60P NCT0PNN. ",
	"\tCTAPT VG60N CQEHS.       ",

	/* Stage select */

	"\tBS60P JTAUA.   ",
	"\tBS60P MNCCNN.    ",

	/* Character select */

	"\tBS60P LEP0R.       ",

	/* Boss attack */

	"\t60CC JTAUS B KAWD0N NCT0PNN.   ",

	/* Dreamcast 2P mode */

	"\tBS60P LPYUUS KH0UKAMN HAUPABV. ",
	"\tBS60P TNUA NLPS. ",
	"\tCVY4ANHSN BS60P TNUA.   ",
	"\tBS60P 60EB0L0 JTAUA.  ",
	"\tBS60P 60EB0L0 JTAUA.  ",

	/* Kart racing */

	"\tBS60P B0DNVS.   ",
	"\tBS60P TPACCS.   ",
	"\tNLPA HA CKA4AHH0N TPACCE.  ",
	"\tUP0BEPKA KAPTS UAMRTN",
	"\tBS60P TPACCS DVR CKA4KN. ",
	"\tHET OANVA TPACCS.    ",
	"\tUP0BEPKA KAPTS UAMRTN",
	"\tOANVS HED0CTYUHS.      ",
	"\tBS60P CQEHS DVR CKA4KN.  ",
	"\tTS X04EZF NLPATF HA JT0N CQEHE?",
	"\tJTAU 60VEE HED0CTYUEH.     ",

	/* Sound test */

	"\tLVABHAR CXEMA C0HNKA 2.      ",
	"\tC 3BYK0BAR CXEMA.  ",
	"\tT 3BYK0BAR CXEMA. ",
	"\tK 3BYK0BAR CXEMA.    ",
	"\tZ 3BYK0BAR CXEMA.   ",
	"\tE 3BYK0BAR CXEMA.   ",
	"\tP 3BYK0BAR CXEMA.  ",
	"\tA 3BYK0BAR CXEMA.",
	"\tMY3SKA 60CC0B.        ",

	"\tBSX0D N3 L0P0DA.",
	"\tK0HF0H.         ",
	"\tTGPFMA.         ",
	"\tLABAHF.          ",
	"\t3EVEHSN VEC.     ",
	"\tTSKBA.           ",
	"\tYVN4HAR MNCCNR.    ",
	"\tB0DHAR ZAXTA.    ",
	"\tKAPT.    ",
	"\tCKPSTAR 6A3A.   ",
	"\tUNPAMNDS.        ",
	"\tUAVATA CMEPTN.    ",
	"\tBE4 DBNLATEVF.     ",
	"\tMETE0PS.        ",
	"\tKPJN3N CAD.      ",
	"\tK0HQ0BKA.      ",
	"\tWEVE3HSE BPATA",
	"\tVALYHA.        ",
	"\t0KEAH UECKA.   ",
	"\t6SCTP0E Z0CCE.      ",
	"\tKBAPTAVS.        ",
	"\tK0V0HNR.        ",
	"\t0PYWENHAR.      ",
	"\t0XPAHA.           ",
	"\tDWYHLVN.         ",
	"\tHE6ECHAR.    ",
	"\tCYMA.         ",
	"\tK0CM0 CTEHA.    ",
	"\tU0L0HR.         ",
	"\tUYZKA.            ",

	"\tCAD 4A0.        ",
	"\tDETCKNN CAD.          ",
	"\t4A0 V066N.     ",
	"\tQEPEM0HNR.         ",
	"\tH0BN40K.          ",
	"\tC0PEBH0BAHNE.      ",
	"\tJHTPAHC.     ",
	"\tDPAL0QEHH0CTN. ",
	"\tCUAPNBAHNE.      ",
	"\t6ELVEQ.     ",
	"\tHALPADA.          ",
	"\tTEMHSN CAD.     ",
	"\tCAD LEP0R.       ",
	"\tTEMHAR TPACCA.",
	"\tTPACCA LEP0R. ",
	"\tOECT TEMHSN CAD.           ",
	"\tOECT CAD LEP0R.            ",
	"\tCAD 4A0.        ",

	"\tCQEHA.    ",
	"\tY6EN B0KPYL.   ",
	"\tCK0P0CTF.   ",
	"\tHEYR3BNM0CTF.      ",
	"\tUVABAHNE.   ",
	"\t1BBEPX.",
	"\tJKPAH UP0D0VWEHNR. ",

	"\t3AL0V0B0K.  ",
	"\tJKPAHH0E MEHG.  ",
	"\t06FRCHEHNE.  ",

	"\t3EVEHSN X0VM.  ",

	/* Unlock stuff messages */

	"\tTS HE M0WEZF BS6PATF\nCQEHY N3 NCT0PNN LEP0R.  ",
	"\tBS60P ATAKN HA BPEMR\nB NCT0PNN LEP0R.                ",
	"\tTS HE M0WEZF BS6PATF\nCQEHY N3 TEMH0N NCT0PNN. ",
	"\tBS60P ATAKN HA BPEMR\nB TEMH0N NCT0PNN.               ",
	"\tBCE JTAUS ATAKN HA BPEMR\nCEN4AC D0CTYUHS.     ",
	"\tMNHN NLPA: KAPT C TPEMR\nTPACCAMN D0CTYUEH.             ",
	"\tMNHN NLPA: KAPT HA 2X\nNLP0K0B D0CTYUEH.           ",
	"\tTS UP0ZEV BCE MNCCNN 3A C0HNKA!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                 ",
	"\tTS UP0ZEV BCE MNCCNN 3A TANVCA!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                 ",
	"\tTS UP0ZEV BCE MNCCNN 3A HYKVNCA!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                        ",
	"\tTS UP0ZEV BCE MNCCNN 3A ZAD0Y!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                      ",
	"\tTS UP0ZEV BCE MNCCNN 3A ELMAHA!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                      ",
	"\tTS UP0ZEV BCE MNCCNN 3A P0YWE!\nTEUEPF BS6NPAN DPYL0L0 LEP0R\nB MYVFTN NLPE.                        ",
	"\tTS UP0ZEV BCE MNCCNN\nC0HNKA C PAHL0M \"A\".         ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.            ",
	"\tTS UP0ZEV BCE MNCCNN\nTANVCA C PAHL0M \"A\".        ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.           ",
	"\tTS UP0ZEV BCE MNCCNN\nHYKVNCA C PAHL0M \"A\".          ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.              ",
	"\tTS UP0ZEV BCE MNCCNN\nZAD0Y C PAHL0M \"A\".           ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.             ",
	"\tTS UP0ZEV BCE MNCCNN\nELMAHA C PAHL0M \"A\".          ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.             ",
	"\tTS UP0ZEV BCE MNCCNN\nP0YWE C PAHL0M \"A\".          ",
	"\tTEUEPF BS6EPN DPYL0L0 LEP0R\nB MYVFTN-NLPE.            ",
	"\tU03DPABVRG!\nTS C06PAV BCE 3HAKN!\nH0BSN JTAU 0TKPST.                      ",

	/* Hero story scene select */

	"HA4AV0       ",
	"BB0D HYKVNC   ",
	"CUACN C0HNKA  ",
	"U06EL N3 TGPFMS     ",
	"BCTPE4A C ZAD0Y     ",
	"L0PA UPN3PAKA ",
	"MNP D0MNHAHTA   ",
	"B0DHAR ZAXTA",
	"LDE ELMAH?     ",
	"CKPSTAR 6A3A ELMAHA ",
	"CTAPT ZATVA      ",
	"K0CM0 K0V0HNR     ",
	"MACTEP N3YMPYDA              ",
	"C0HNK B 6EDE    ",
	"ZAHC       ",

	/* Dark story scene select */

	"HA4AV0       ",
	"BB0D P0YWE ",
	"CKPSTAR 6A3A      ",
	"UP0ZV0E ZAD0Y",
	"BX0D B CKPSTYG 6A3Y   ",
	"C060P TFMS           ",
	"6EPN N3YMPYD XA0 ",
	"BCTPE4A C0HNKA     ",
	"NMUEPNR ELMAHA   ",
	"U0CVEDHNN N3YMPYD ",
	"UEPEX0D CKPST0N 6A3S ",
	"BCTPE4A C HYKVNC0M    ",
	"UVAH ELMAHA  ",
	"TANHA ZAD0Y      ",
	"U0CVEDHNN 60N  ",

	/* Last story scene select */

	"HA4AV0       ",
	"U0CVEDHRR MNCCNR",
	"K0HE4HSN 60N       ",
	"HADEWDS       ",

	/* World ranking and network connection stuff (unused) */

	"WMN Y DVR 06H0BVEHNR          ",
	"ATAKA HA BPEMR           ",
	"C4ET ATAKN                ",
	"3HAKN               ",
	"06ZNN C4ET   ",
	"UP0CM0TP C4ETA          ",
	"UP0CM0TP C4ETA          ",
	"K0MEHTAPNN        ",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"\tPAHLN HA JKPAH               ",
	"\tCUNC0K PAHL0B.         ",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"\tKH0UKA B\n06PATH0.                        ",

	/* Hero story recaps */

	//City Escape
	"R C0HNK! EWNK B TYMAHE!       ",
	"BHE3AUH0 U0KA3AVNCF B0NCKA.\nL0B0PRT 0HN NCKAVN MEHR.\nM0WET 0HN UP0KATRT MEHR\nKYDA-HN6YDF!                                        ",
	"JN! 4T0 JT0? HAPY4HNKN?\nU0D0WDNTE!\n0 4EM JT0 BS?\nR HE DE3EPTNP\nN3 APMNN!                                              ",
	"R DYMAV, 4T0 JT0\nZYTKA, H0 JT0 HE CMEZH0!                   ",
	"HAD0 NDTN 0TCGDA!       ",

	//Big Foot
	"R C0HNK! EWNK B TYMAHE!       ",
	"4T0 3A YUPRMSE 0CVS!\nDA KT0 0HN B00ZE\nTAKNE?                                 ",
	"0HN HE T0VFK0 CVEDRT 3A MH0N\nDEHF N H04F, H0 0HN EZE\nUPNBEVN CGDA JT0L0 P060TA\n4T06S U0NMATF MEHR.",
	"0HN X0TRT MEHR U0NMATF\nHA JT0T PA3!                    ",
	"H0 0HN DYMAG, 4T0 JT0\nCPA60TAET? R U0KAWY NM\nUPNEM4NKN...DANTE MHE\nTPN MNHYTS, 4T06S C06PATFCR!                              ",

	//Wild Canyon
	"R EXNDHA HAKVC.\nH0 30BNTE MEHR UP0CT0 HAKVC.           ",
	"EZE PA3, N3YMPYD\nYKPAVN C 0CTP0BA AHLEV0B.                  ",
	"B0P0M 0KA3AVACF JTA\nN3BECTHAR DEB40HKA\nVETY4AR MSZF.              ",
	"K0LDA 0HA 6SVA B M0EN\nD0CRLAEM0CTN, KT0 BS DYMAETE U0KA3AVCR?\nDA. BEPH0, JLMEH!\n0H U0RBNVCR N NCU0PTNV\nM0N UVAHS N USTAVCR 3A6PATF\nN3YMPYD!                                   ",
	"MHE YDAV0CF PA36NTF\nN3YMPYD HA KYC04KN\nD0 T0L0 KAK JLMAH\nYVN3HYV. TEUEPF HAD0 HANTN\nKYC04KN.                     ",
	"TA DEB40HKA\nT0WE NZET KYCKN.\nR D0VWEH C06PATF NX N CKVENTF\nN3YMPYD KAK M0WH0 6SCTPEE!                           ",

	//Eggman 1
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"R CM0TPEV TEVNK N YCVSZAV\nH0B0CTN.\nR 6SV Z0KNP0BAH\nYBNDEB C0HNKA.                       ",
	"C0HNKA APECT0BAVN 3A\n4T0-T0 YWACH0E,\n4T0 HE U0X0WE HA C0HNKA.             ",
	"HE M0LY U0BEPNTF, 4T0 JT0 UPABDA\nR UPSLHYV B T0PHAD0\nN HAUPABNVCR CPA3Y K\n0CTP0BY TGPEM.            ",
	"N D0LADANTECF HA K0L0 R\nHATKHYVCR? JLMEH! 0H 0URTF\n4T0-T0 3AMSZVRV!\n0H UPECVED0BAV JMN!            ",
	"BPEMR T0PM03NTFT0PHAD0 N\nCUCATF JMN!               ",
	"T0PHAD0 TPAHCO0PMAQNR! ",

	//Prison Lane
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"R CUAC JMN 0T JLMAHA,\n0HA CKA3AVA, 4T0 JLMAH,\nHA JT0T PA3 3ATERV 4T0-T0\nLPAHDN03H0 YWACH0E!                                           ",
	"HAD0 U0HA6VGDATF 3A HNM.\nH0 CHA4AVA HAD0 CUACTN\nC0HNKA!                ",
	"4T0 JT0?\nTS T0WE X04EZF U0NTN?\nECVN X04EZF,\nBCE BU0PRDKE.\nT0VFK0 HE UYTANCR U0D H0LAMN!               ",

	//Metal Harbor
	"R C0HNK! EWNK B TYMAHE!       ",
	"4T0 3DECF\nDEVAET JMN?               ",
	"HEBAWH0...HAD0 CK0HQEHTPNP0BATFCR\nHA U0NCKAX 4EPH0L0 EWNKA, K0T0PSN\nU0X0W HA M0G TEHF! 0H\nLDE-T0 HA JT0M 0CTP0BE\nR 3HAG!           ",
	"R TEPRG BPEMR!\nR UEPEXNTPG CTPAWY\nN YNDY 0TCGDA!                                   ",
	"JT0 3HA4NT, 4T0\nR DE3EPTNP?            ",

	//Shadow 1
	"R C0HNK! EWNK B TYMAHE!       ",
	"R 6SCTP0 C6EWAV\nN3 TGPFMS!\nN R HAZEV TEHF!                     ",
	"0H HE Y6EWAV 0T MEHR T0LDA!  ",

	//Green Forest
	"R C0HNK! EWNK B TYMAHE!       ",
	"R U04TN U0NMAV TEHF,\nH0 Y MEHR HE 6SV0\nBPEMEHN. HAD0 T0P0UNTFCR!     \nJLMAH CKA3AV, 4T0\n0H B30PBET JT0T 0CTP0B\n4EPE3 URTF MNHYT!              ",
	"JLMAH CKA3AV, 4T0\n0H B30PBET JT0T 0CTP0B\n4EPE3 URTF MNHYT!              ", //unused
	"R D0VWEH Y6NPATFCR C\n0CTP0BA N 6SCTP0!\nLDE JMN N TENVC!         ",

	//Pumpkin Hill
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"CVEDYR 3A CNLHAV0M,\nNCX0DRZNM 0T N3YMPYDA,\nR U0UAV B JT0T\nCEVFCKNN KAHF0H!                          ",
	"CTPAZH0BAT0, H0\nR HE 60GCF UPN3PAK0B!          ",
	"HAD0 HANTN KYC04KN\nN3YMPYDA!                        ",

	//Mission Street
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"JLMAH 06FRBNV\n4T0 0H X04ET\n3AXBATNTF MNP!                   ",
	"0H B30PBAV U0V-VYHS\nJTNM M0ZHSM 0PYWNEM\nTEUEPF 0H X04ET 3AXBATNTF UVAHETY!\nH0 JT0MY HE 6SBATF!                                             ",
	"JLMAHY HYWHS\nN3YMPYDS, 4T06S\n3AUYCTNTF 0PYWNE.                               ",
	"BCE 3ABNCNT 0T MEHR!\nR HANDY JLMAHA\nN N3YMPYDS!            ",
	"CHA4AVA HAD0 CUPRTATFCR\nB HADEWH0M MECTE!  ",

	//Aquatic Mine
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"CVEDR 3A CNLHAV0M\n0T N3YMPYDA,\nR U0UAV B JT0T\nKAHF0H.                                ",
	"JT0 MECT0 U0X0WE HA\n3A6P0ZEHYG ZAXTY.\n60VFZAR 4ACTF EE B B0DE!                  ",
	"6YDET HEVELK0 HANTN\nKYC04KN N3YMPYDA.\nH0 HET BPEMEHN WAV0BATFCR.                                   ",
	"R D0VWEH 6SCTP0 HANTN\nKYC04KN N3YMPYDA!                 ",

	//Route 101
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"R UP0CVEDNV CNLHAV\nN3YMPYD0B N\n06HAPYWNV JLMAHA.                ",
	"4T0 JLMAH DEVAET\nB K0CM0CE?        ",
	"6E3 UAHNKN.\nHAD0 0UPEDEVNTF\nT04HSE K00PDNHATS JLMAHA!                 ",
	"HE B0VHYNCR JMN!\nU0MHN, R \"MAL\" K0LDA\nPE4F NDET 0 MAZNHAX!                 ",
	"R HANDY UPE3NDEHTA!     ",

	//Hidden Base
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"MS UP0KATNVNCF HA\nVNMY3NHE UPE3NDEHTA N 4T0?\nMS 06HAPYWNVN, LDE\nUPR4ETCR JLMAH! ",
	"JLMAH HA K0V0HNN APK\nB K0CM0CE.                     ",
	"0CTAV0CF HANTN 6A3Y JLMAHA\nB UNPAMNDE LDE-T0 B\nUYCTSHE!                    ",
	"HAZEV! U0NDY BUEPED N\nHANDY BX0D.           ",

	//Pyramid Cave
	"R C0HNK! EWNK B TYMAHE!       ",
	"HAM YDAV0CF 3A6PATFCR\nB UNPAMNDY N HANTN\n6A3Y JLMAHA!              ",
	"D0VWEH 6STF CU0C06\nYVETETF B K0CM0C 0TCGDA.\nY HAC MAV0 BPEMEHN,\nU0ZVN!                     ",

	//Death Chamber
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"HAM YDAV0CF 06HAPYWNTF\n6A3Y JLMAHA LVY60K0\nB UNPAMNDE.               ",
	"TEUEPF HAM HAD0\nHANTN KVG4F N 0TKPSTF DBEPF\nN BS6PATFCR HAPYWY.        ",
	"4T0? 3A4EM MHE NCKATF\nKVG4N? JT0 HE M0R PA60TA,\nH0 R JT0 CDEVAG. \nR D0VWEH PADN\nLVABH0L0 N3YMPYDA!                        ",
	"R U0KAWY TE6E,\n4T0 MEHR DEVAET\nVY4ZNM 0X0THNK0M 3A C0KP0BNZAMN!    ",

	//King Boom Boo
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"JT0 6SV KYC0K UNP0LA!\nR HAZEV KVG4 N TEUEPF\nHAD0 NCCVED0BATF\n6A3Y JLMAHA.                   ",
	"4T0 JT0?\nY MEHR UV0XNE UPED4YBCTBNR!\n3DECF WYDK0. 3DECF M0LYT\n6STF DYXN LP06HNQS?                                  ",
	"HE DYMAG, 4T0 M0LY\nCUPABNTFCR C JTNM, H0 KAK\nR T0LDA HANDY\nKYC0K N3YMPYDA?\nY MHER HET BS60PA!                          ",

	//Egg Golem (hero)
	"R C0HNK! EWNK B TYMAHE!       ",
	"6VAUL0DAPR HAKVCY\nHAM YDAV0CF H0TKPSTF\nDBEPF 0T 6A3S JLMAHA.                ",
	"JLMAH U0RBNVCR HE0TKYA\nN CHNM U0RBNVACF\nL0P0MHAR CTATYR!    ",
	"JT0T JLMAH!\n0TKYDA 0H Y3HAV\n 0 HAC?               ",
	"TS DYMAEZF, 4T0\nKAMEHF 0CTAH0BET HAC?              ",

	//Eternal Engine
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"HAM YDAV0CF 3AUYCTNTF\nZATV JLMAHA\nHA CEKPETH0N 6A3E N MS\nUPNVETEVN HA K0V0HNG APK.                              ",
	"JT0 6SVA M0R NDER\nYHN4T0WNTF 0PYWNE\nC U0M0ZFG VWE-N3YMPYDA!         ",
	"NHTEPECH0, C0HNK\nU0HNMAET UVAH?        ",
	"MHE HAD0 CHA4AV0 HANTN\nNCT04HNK JHEPLNN!        ",

	//Meteor Herd
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"JT0T KYC0K N3YMPYDA\nK0T0PSN R HAZEV\nTEUEPF VETAET B B03DYXE.\nHAD0 HADEWHEE NX\n0XPAHRTF B LPY30B0M\n0TCEKE!                           ",
	"JT0 HE VELK0\n0XPAHRTF N3YMPKD\n3HAEZF?                        ",
	"R D0VWEH HANTN NX\nU0KA MS NX HE U0TEPRVN 0URTF",

	//Rouge
	"R HAKVC EXNDHA.\n30BNTE MEHR UP0CT0 HAKVC.       ",
	"U0CVE T0L0 KAK MS\nHAZVN U0V0BNHY KYC04K0B\nR M0LY U0NTN K T0N DEB40HKE!                  ",
	"YBEPEH, Y HEE BT0PAR\nU0V0BNHA KYC04K0B.\nHE BPEMR DVR PA3L0B0P0B!\nHAD0 DATF EN ZAHC!             ",
	"HAD0 BEPHYTF\nTE KYCKN!            ",

	//Crazy Gadget
	"R C0HNK! EWNK B TYMAHE!       ",
	"HAZ UVAH ZEV NDEAVFH0\nU0KA JLMAH HE CXBATNV JMN!",
	"JLMAH CKA3AV, 4T0 06MEHRET\nJMN HA N3YMPYDS...\nHAD0 UPNDYMATF 4T0 DEVATF!         ",
	"HE BPEMR DVR ZYT0K!\nJLMAH L0T0B\nUPNMEHNTF 0PYWNE!                   ",
	"TENVC, JMN, DEPWNTECF\nR NDY!   ",

	//Eggman 2
	"MEHR 30BYT MANVC,\nH0 30BNTE MEHR UP0CT0 TENVC.       ",
	"C0HNKA U0NMAVN N\nU0MECTNVN B KAUCYVY. JLMAH\nBSUYCTNV KAUCYVY B\nK0CM0C N B30PBAV EE!            ",
	"HET JT0 HEUPABDA!\nC0HNK HE U0LN6!         ",
	"JLMAH! R HE DAM TE6E\nYNTN C JTNM!\nR 06EZAV, 4T0 HE CDAMCR N\nCDEPWY 06EZAHNE.\nTS 3A JT0 3AUVATNZF!                       ",

	//Final Rush
	"R C0HNK! EWNK B TYMAHE!       ",
	"R YVN3HYV N3\nV0BYZKN JLMAHA C\nU0M0ZFG K0HTP0VR\nXA0C!                          ",
	"0CTAV0CF MAV0 BPEMEHN\nUPEWDE 4EM 0PYWNE BSCTPEVNT!       ",
	"R 6P0ZY JTN N3YMPYDS\nB UYZKY D0 T0L0\nKAK 0HA BSCTPEVNT!                     ",

	//Shadow 2
	"R C0HNK! EWNK B TYMAHE!       ",
	"BPEMR UP0TNB HAC!\nK0LDA R DYMAV, 4T0 BCE\nU0D K0HTP0VEM,\nU0RBNVACF TEHF.\nR D0VWEH 3AK0H4NTF JTY 6NTBY\nUP0TNB 4EPH0L0 EWNKA!                                 ",
	"U0KAWN MHE HA 4T0 CU0C06EH!\nHACT0RZAR CNVA!           ",

	/* Dark story recaps */

	//Iron Gate
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"CVY4ANH0,\nR HAZEV DHEBHNK M0EL0 DEDA.\nB HEM 0H 0UNCSBAET MNCTN4ECK0E\nCEKPETH0E 0PYWNE\nU0D HA3BAHNEM \"UP0EKT TEHF\".                        ",
	"DHEBHNK HABEPH0E 6SV 3AUE4ATAH\nBHYTPN B0EHH0-NCCVED0BATEVFCK0L0\nK0MUVEKCA, 3AXBA4EHH0L0\n50 VET HA3AD.             ",
	"NCCVED0BAHNE 6SV0 YTPA4EH0!   ",
	"HACVEDNE BEVNK0N Y4EHH0N\nMSCVN B NCT0PNN MNPA N 4EV0BE4ECTBA,\nUP0OECC0P LEPAVD. JT0 M0N DED!                ",
	"N3 JT0L0 M0WH0\nN3BVE4F K0E-KAKYG U0VF3Y",

	//Hot Shot
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"UP0CHYBZNNCR U0CVE\nD0VL0L0 CHA B 50 VET.           ",
	"D0KT0P JLMAH,\nBHYK M0EL0 C03DATEVR,\n0CB060DNV MEHR.                      ",
	"D0KT0P PA36YDNV MEHR\nN 3A JT0 R D0VWEH NCU0VHNTF\nEL0 WEVAHNE.  ",
	"CHA4AV0 R U0KAWY\nM0G CNVY.\n3A 10 CEKYHD R M0LY YHN4T0WNTF\nQEVYG APMNG\nKAK NLPYZKY!                                        ",

	//Dry Lagoon
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"R VG6VG DPAL0QEHH0CTN\nN MHE BCELDA NX MAV0!\nR HAZVA LVABHSN N3YMPYD, H0...                                 ",
	"JTA EXNDHA\nCVEDNT 3A MH0N.\n0H 04EHF HACT0N4NBSN!                ",
	"60VEE T0L0 JT0T CTAPNKA\nC U0D03PNTEVFHSMN YCAMN\nUSTAVCR 0THRTF EL0 Y MEHR,\nH0 0H PA3VETEVCR HA MEVKNE KYC04KN.                                   ",
	"CM0TPN 4T0 TS HADEVAV!    ",
	"TEUEPF MHE HYWH0\nHANTN N C06PATF KYC04KN!         ",

	//Sand Ocean
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"R 0CB060DNV TEHF\nN3 EL0 3AKVG4EHNR\nH0 TEUEPF...                 ",
	"TEHF CKA3AV MHE UPNHECTN\nN3YMPYD XA0C NA\nUPNC0EDNHNTCR K K0V0HNN, APK.          ",
	"HABEPH0E 4T0-T0 UP0NCX0DNT.\nHYWH0 BEPHYTCR HA 6A3Y\nN UP0BEPNTF!                 ",

	//Radical Highway
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"R B3RV N3YMPYD XA0CA\nN3 HAQN0HAVFH0L0 6AHKA.            ",
	"N CEN4AC B0EHHSE N\nU0VNQNR UPECVEDYGT MEHR.\n0HN MEHR HNK0LDA HE U0NMAGT.\nJT0 UYCTAR TPATA BPEMEHN!                                           ",
	"HET BPEMEHN DVR NLP.\nMHE HYWH0 YX0DNTF 0TCGDA!             ",

	//Egg Quarters
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"MHE YDAV0CF U0V0WNTF TPAHCMNTEP\nB MAZNHY CTAPNKA\nK0LDA 0H U0RBNVCR.              ",
	"U0KA R HE M0LY CKA3ATF U04EMY...",
	"3ATEM R U0ZEV 3A HNM B\nEL0 UNPAMNDY,\nH0 R HE CM0L B0NTN\nDBEPF 6SVA 3AKPSTA.                      ",
	"MHE HYWH0 HANTN\nKVG4 4T06S B0NTN.                      ",

	//Lost Colony
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"R U0ZEV B K0V0HNG APK,\nKAK TEHF CKA3AV MHE.             ",
	"KAKAR K0MHATA APK\nLVABHAR?\nHAD0 BSRCHNTF!                         ",

	//Weapons Bed
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"P0YL UPNC0EDNHNVACF K HAM\nN MS BEPHYVNCF HA 0CTP0B.                      ",
	"MS UPNZVN CGDA, 4T06S\nHANTN N3YMPYD XA0CA,\n0H LDET0 3DECF\nHA B0EHH0N 6A3E.                           ",
	"R B0NDY CHA4AVA\nN YHN4T0WY B0NCKA.\nU0T0M MS PA3PA60TAEM UVAH!                    ",

	//Tails 1
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"K0LDA MS D06PAVNCF\nD0 6A3S, 4T06S 3A6PATF\nN3YMPYD XA0CA,\nHAC TAM KT0-T0 0CTAH0BNV!                    ",
	"TEHF N P0YL NDNTE!\nR 0 HEM U03A604YCF!!        ",
	"Y6NTF TE6R 0DH0\nYD0B0VFCTBNE, XNTPEQ!    ",

	//Security Hall
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"R B0ZEV HA\nB0EHHYG 6A3Y, TAK KAK,\nUVAHNP0BAV D0KT0P.                       ",
	"MHE HYWH0 HANTN\n0CTABZNECR TPN N3YMPYDA XA0CA.\nN BCE 6YDET 0TVN4H0!               ",

	//Flying Dog
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"KAZMAP.\nKAK R M0LY D0UYCTNTF\nTAK0E?!                           ",
	"K0LDA C06PAV\nTPN N3YMPYDA XA0CA,\n4T0-T0 UPNBVEKV0 M0E BHNMAHNE!\nN BDPYL...            ",
	"CPA60TAVA CNLHAVN3AQNR\nN R 6SV 3AUEPT B CENOE!                ",
	"0TKYDA HE B03FMNCF,\nU0RBNVCR B0NH.\n0CTAUV0CF MAV0 BPEMEHN\nD0 T0L0 KAK 60M6A TEHN\nB30PBETCR!\nCEL0DHR UV0X0N DEHF!                                         ",
	"CHA4AVA\nHAD0 3AHRTFCR DEVAMN.            ",

	//White Jungle
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"U0X0WE DEB40HKA\nHE CUPABNVACF C 3ADAHNEM.              ",
	"HE HAD0 0 HEN\n6ECU0K0NTFCR, HAD0 DYMATF\n0 CUACEHNN N3YMPYDA!               ",
	"HAD0 CUEZNTF, CK0P0\nB30PBETCR 60M6A.                                        ",

	//Sonic 1
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"DPYL0N EWNK U0RBNVCR\nK0LDA R ZEV\nCUACATF P0YL.                     ",
	"0H MEHR PA3DPAWAET.\nU0PA U0KA3ATF CB0G CNVY!                  ",

	//Route 280
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"MS 3ARBVREM 0 HAMEPEHNN\n3AXBATNTF MNP C U0M0ZFG\nCNVS N3YMPYD0B YKPADEHHSX\nC B0EHH0N 6A3S.                                      ",
	"UYZKA 3ATMEHNR 6YDET\n3APRWATFCR D0VL0!         ",
	"HAD0 D0CTATF U0CVEDHNN\nN3YMPYD, 6SCTP0!\nLDE VNCEH0K?                       ",

	//Sky Rail
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"R U0VY4NV U0CVAHNE 0T\nP0YL N CVEDYG UVAHY...\nUNV0T0M 3ABVADEV\nU0CVEDHNN N3YMPYD.                             ",
	"BUEPEDN CT0VFK0\nCTPAZHSX L0P...\nHE B0VHYNCR,\nR HE YUYZY CAM0VET!                                          ",

	//Egg Golem (dark)
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"R WDAV C0HNKA B\nCUPRTAHH0N 6A3E, 4T06S U0KA3ATF\nKVACCH0L0 P060TA\nK0T0P0L0 R CDEVAV...                                ",
	"JT0T L0VY60N EWNK 0URTF MEHR U0DBEV!\nTEUEPF 0H MEHR ATAKYET.\nU04EMY TAK UP0NCX0DNT?                             ",
	"YX0DN C M0EN D0P0LN!\nC0HNK Y6ELAET!      ",

	//Mad Space
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"H0 JT0 EZE HE BCE...      ",
	"HAKVHEQ-T0 U0RBNVNCF PE6RTA,\nK0LDA R BEPHYVCR C\nCEKPETH0L0 3ADAHNR. ",
	"0HN HAZVN 0CTAVFHSE\nKYCKN LVABH0L0\nN3YMPYDA. J0 M0N ZAHC!                                 ",
	"R HAZEV NHO0PMAQNG 0 CEKPETH0M\nUP0EKTE, \"TEHF\",\nTEUEPF MHE HAD0\nCXBATNTF LVABHSN N3YMPYD!                              ",

	//Knuckles
	"MEHR 30BYT P0YL,\nR 0X0THNK 3A C0KP0BNZAMN.                           ",
	"0H DENCTBYET MHE HA HEPBS!\n0H NHTEPECYETCR\nN3YMPYD0M? U04EMY 0H\nHE CDAETCR?\nJTA BPEDHAR EXNDHA.                                            ",
	"R U06FG EL0 N 0T6EPY\nN3YMPYD!                  ",

	//Cosmic Wall
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"C0HNK N EL0 DPY3FR\nHAZVN CU0C06\nD06PATFCR D0 K0V0HNN.                ",
	"U04EMY R U0VY4AG\nCNLHAVS 0T DBYX N3YMPYD0B?\nB 4EM DEV0!                     ",
	"0HN UVAHNPYGT\nK0HTPATAKY.              ",
	"HEVF3R TEPRTFBPEMR!\nHAD0 BEPHYTFCR B K0V0HNG\nN ATAK0BATF NX.       ",

	//Tails 2
	"R BEVNKNN JLMAH\nLEHNN HAYKN MNPA!                           ",
	"XAXAXAXAXA!\nU0VY4NV0CF! R U06EDNV C0HNKA!\nBPEDHSN EWNK\nYZEV HABCELDA!\nTEUEPF 0H L0PA\nMYC0PA B K0CM0CE!                                         ",
	"4T0 TS DEVAEZF, TENVC?\nECVN TS UP0TNB MEHR,\nTE6R U0CTNLHET\nTAWE Y4ACTF.                                     ",

	//Final Chase
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"TEUEPF BCE N3YMPYDS\nHA MECTE.\nTEUEPF YCTAH0BKA L0T0BA,\nBCE U04TN L0T0B0!                          ",
	"BCE JT0 BPEMR KT0-T0 USTAVCR\nUP06PATFCR K UYZKE.\nTEUEPF Y HNX HET ZAHCA!                         ",
	"BAWH0, 4T06S MS HE D0UYCTNVN\n0ZN60K.\nHAD0 N36ABNTFCR\n0T JTNX YP0D0B!                              ",

	//Sonic 2
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"JT0T EWNK X04ET\nYHN4T0WNTF UYZKY!                                   ",
	"U0PA3NTEVFH0.\nR DYMAV 0H YMEP B KAUCYVE\nB K0CM0CE.                       ",
	"TEUEPF R 3HAG, 4T0 EWNK\n04EHF 0UACEH!       ",
	"K0LDA R PA36EPYCF C HNM,\n0H U0WAVEET, 4T0 HE YMEP B KAUCYVE.\nR U0KAWY EMY M0G CNVY.                    ",

	/* Last story recaps */

	//Cannon's Core
	"MEHR 30BYT JMN.\nR KPYTAR!                        ",
	"UP0NCX0DNT 4T0-T0YWACH0E!\nUP0OECC0P 3AUYCTNV\nJTY UP0LPAMMY 04EHF DABH0.                  ",
	"JTA UP0LPAMMA C06FET\nK0V0HNG C EE 0P6NTS N\n3ACTABNT YUACTF HA 3EMVG.\n0HA YWE UADAET!                                     ",
	"U0X0WE JLMAH\n06MAHYV TEHF.           ",
	"0H 04EHF 3V0N!\nHAM HAD0 0CTAH0BNTF\nK0V0HNG.                                                              ",
	"HAD0 D06PATFCR D0\nRDPA K0V0HNN N\n0CTAH0BNTF CNVY N3YMPYDA.                               ",
	"Y HAC MAV0 BPEMEHN!\nC06PAVNCF N CDEVAEM JT0!                  ",

	//The Biolizard
	"R EWNK - TEHF.\nC0BEPZEHHAR O0PMA WN3HN.                      ",
	"6VAL0DAPR JMN R\nBCU0MHNV WEVAHNE MAPNN.            ",
	"K0LDA R JT0 U0HRV,\nC0BEPZEHHAR WN3HF\nU0USTAVACF 0CTAH0BNTF MEHR.         ",
	"R PA36EPYCF C JTNM C0HNK!\nTS 0CTAH0BN CNVY\nN3YMPYD0B.                               ",

	//The Finalhazard
	"R C0HNK! EWNK B TYMAHE!       ",
	"HAM YDAV0CF 0CTAH0BNTF N3YMPYDS\nH0 K0V0HNR\nUP0D0VWAET UADATF.                              ",
	"WN3HF CTAVA EDNH0N\nC K0V0HNEN N HAUPABVRET EE\nK 3EMVE.                                                 ",
	"K0V0HNR CK0P0 B0NDET\nB ATM0COEPY.\nHAD0 EE YHN4T0WNTF!                                    ",
	"C0BEPZEHHAR WN3HF UNTAETCR\nHAZNMN WEVAHNRMN. R\nU0KAWY CNVY CYUEP C0HNKA!           "
};

std::vector<const char*> PauseMenuVector
{
	"\aDAVFZE  ",
	"\aCH0BA  ",
	"",
	"",
	"",
	"\aYNTN"
};

#pragma endregion

void WriteAdvertise(const std::vector<const char*>& advertise)
{
	int size = advertise.size();

	for (int i = 0; i < size; i++)
	{
		if (strlen(advertise[i]) != 0)
		{
			AdvertiseGamepad[i] = advertise[i];
			AdvertiseKeyboard[i] = advertise[i];
		}
	}
}

void WritePauseMenu(const std::vector<const char*>& pauseMenu)
{
	int size = pauseMenu.size();

	for (int i = 0; i < size; i++)
	{
		if (strlen(pauseMenu[i]) != 0)
		{
			PauseMenu[i] = pauseMenu[i];
		}
	}
}

void WriteRemainingText()
{
	WriteData((const char**)0x173A95C, "NOW SAVING"); //"Saving..."
	
	WriteData((const wchar_t**)0x401648, L"Вы действительно хотите выйти из игры?\nВесь несохранённый прогресс будет утерян."); //exit prompt
	WriteData((const wchar_t**)0x174F59C, L"Да");
	WriteData((const wchar_t**)0x174F55C, L"Нет");
	WriteData((wchar_t*)0x89DD14, L"SONIC ADVENTURE 2: Предупреждение"); //exit message box title
}


void InitExeText()
{
	if (GetTranslationType() == "Kudos")
	{
		WriteAdvertise(AdvertiseKudos);
		WritePauseMenu(PauseMenuKudos);
	}
	else
	{
		WriteAdvertise(AdvertiseVector);
		WritePauseMenu(PauseMenuVector);
	}
	
	WriteRemainingText();
}