#pragma once


const std::vector<const char*> AdvertiseKudos
{
	/* Main menu */

	"\t0DNH NZP0K        ",
	"\t2N PEWNM      ",
	"\tYC0BEPGEHCTB0BATS                    ",
	"",
	"",
	"",
	"\tYX0D",

	/* Help & options */

	"\tQKCTPA MEHU",
	"",
	"",
	"",
	"\t0JVNN         ",
	"",

	/* Single player */

	"\tNZPA J0 NCT0PNN.          ",
	"\tBF60P CVEHF.                ",
	"\tNZPA J0 CTADNRM.            ",

	/* Some 2P mode stuff */

	"\tECTS 3 TNJA NZP.           ",
	"\tQT0 KAPT Z0H04H0N NZPF.      ",
	"\t4A0 YBELN4NTS    D0      (8) 4A0. ",

	/* Extras */

	"\tYC0BEPGEHCTB0BATS                    ",	//world ranking
	"\t0MAX0 06SRCHNT NZPY.          ",			//tutorial
	"\tJ0KA3ATS CJNC0K C06PAHHFX QM6LEM.     ", //emblem results
	"\tNZPATS 4EPE3 3AZPY3KY  ",				//DLC

	/* Memory card select (console leftover) */

	"\tBF60P JAMRTN         ",
	"\tHET MECTA DLR C03DAHNR OANLA.   ",

	/* File select */

	"\tBF60P OANLA.  ",
	"\tC03DATS H0BFN OANL",
	"\t3AZPY3NTS   ",
	"\tYDALNTS QT0T OANL?              ",
	"\tHET MECTA DLR C0XPAHEHNR 4A0.      ",

	/* Options */

	"\tCLYGAN MY3FKY.",
	"\tCTEPE0/M0H0 0JVNN.   ",
	"\tBF60P JPFWK0B             ",
	"\tBF60P R3FKA                        ",
	"\tBF60P OANLA.",
	"\tBF60P TEMF QKPAHA.       ",
	"\tBF60P  PAL TV YCTAH0B.",
	"\tCTEPE0 3BYK            ",
	"\tM0H0 3BYK                ",
	"\tJPFW0K BKL.  ",
	"\tJPFW0K BFKL.  ",
	"\tAHZLNNCKAR NCT0PNR",
	"\tRJ0HCKAR NCT0PNR.  ",
	"\tPYCCKNE CY6TNTPF ",
	"\t----------------  ",
	"\t----------------",
	"\t----------------",
	"\t-----------------",

	/* Sound test general */

	"\tBF60P MEL0DNN                        ",
	"\tBF60P JECHN NLN MY3FKN              ",

	/* Menu themes */

	"\tHAD0 3AZPY3NTS OANLF NCT0PNN",
	"\tBF60P NCT0PNN  ",
	"\t3AZPY3NTS NCT0PNN. ",
	"\tHEB03M0WH0 3AZPY3NTS      ",
	"\tHET OANL0B NCT0PNN.    ",
	"\tCKA4ATS C BE6CANTA         ",

	/* TV settings */

	"\tC0BMECTNM0CTS C TELEBN30P0M 60ZV",
	"\tJ0KAWEM KAPTNHKN HA 5 CEKYHD       ",
	"\tECLN K0PPEKTH0, 60 ZV C0BMECTNM0     ",
	"\t50ZV         ",
	"\tJ0KA3AH0 HA JAL TELEBN30PE        ",
	"\t60ZV         ",
	"\t60ZV TPE6YETCR             .",

	/* Separate string for Italian language */

	"",

	/* Progression percentage (unused) */

	"H0B",
	"10%JP0ND",
	"20%JP0ND",
	"30%JP0ND",
	"40%JP0ND",
	"50%JP0ND",
	"60%JP0ND",
	"70%JP0ND",
	"80%JP0ND",
	"90%JP0ND",

	/* Story select */

	"\tBF60P NCT0PNN  ",
	"\tHA4ATS CVEHY HA BF60P    ",

	/* Stage select */

	"\tBF60P CTADNN   ",
	"\tBF60P MNCCNN     ",

	/* Character select */

	"\tBF60P CTATYCA      ",

	/* Boss attack */

	"\tNZPA 60CC-CTADNN B NCT0PNN     ",

	/* Dreamcast 2P mode */

	"\tBF60P ZPYJJF C           D-pad.",
	"\tBF60P TNJA NZPF  ",
	"\tCLY4ANHAR NZPA          ",
	"\tBF60P CPAWEHNR        ",
	"\tBF60P CPAWEHNR        ",

	/* Kart racing */

	"\tB0DNTELS        ",
	"\tHAJPABLEHNE     ",
	"\t3AZPY3NTS  HAJPABLEHNE     ",
	"\tJP0BEPKA KAPTF JAMRTN",
	"\tBF60P 3AZPYWAEM0Z0 HAJP. ",
	"\tHE HANDEH0           ",
	"\tJP0BEPKA KAPTF JAMRTN",
	"\tHE HANDEH0             ",
	"\tBF60P 3AZPYWAEM0Z0 C06FT.",
	"\tX0TNTE NZPATS C QTNM C06FTNEM? ",
	"\tCTADNR J0KA HE D0CTYJHA    ",

	/* Sound test */

	"\t3BYK.JPNKLU4EHNE 2 CVEHF.    ",
	"\tLENTM0TNB 3BYK0B   ",
	"\tLENTM0TNB XB0CT0B.",
	"\tLENTM0TNB K0CTRGEK   ",
	"\tLENTM0TNB TEHEN     ",
	"\tLENTM0TNB QZMQHA    ",
	"\tLENTM0TNB PYMRH    ",
	"\tLENTM0TNB QMN    ",
	"\tMY3FKA DLR 60CC-CTADNN",

	"\tJ06EZ       6WM.",
	"\tKAHS0H      6MW.",
	"\tTUPSMA      6WM.",
	"\tMETAL ZABAHS 6WM.",
	"\t3ELEHFN LEC  6WM.",
	"\tTFKBEHH.X0LL 6WM.",
	"\tYLN4HAR MNCCNR 6WM.",
	"\tB0DHAR MNHA  6WM.",
	"\tKAPT 6WM.",
	"\tCKPFT. 6A3A 6WM.",
	"\tJEGEPA       6WM.",
	"\tKAMEPA CMEPT. 6WM.",
	"\tBE4HFN DBNZAT. 6WM.",
	"\tCTAD0       6WM.",
	"\tH0BNHKA      6WM.",
	"\tZ0HKA ONH. 6WM.",
	"\tB0P0TA    6WM.",
	"\tZP.LAZYHA  6WM.",
	"\t0KEAH JEC4.6WM.",
	"\tMAZNCTPALS      6WM.",
	"\tRNVEDELNTELS 6WM.",
	"\tJ0T.K0L0HNR 6WM.",
	"\t0PYWEHNR    6WM.",
	"\t3AL 0XPAHF    6WM.",
	"\t6EL.DWYHZLN  6WM.",
	"\t0ZPADA   6WM.",
	"\tK0CM0C    6WM.",
	"\tCTEHA K0CM. 6WM.",
	"\tONH.J0Z0HR  6WM.",
	"\tRDP0 JYGEK    6WM.",

	"\t4A0 CAD     6WM.",
	"\t4A0 DETCKNN CAD   6WM.",
	"\t4A0 L066N  6WM.",
	"\tHAZPAWDEHNE    6WM.",
	"\tHA4ALSHAR     6WM.",
	"\tC0CTR3AHNE     6WM.",
	"\tBX0D     6WM.",
	"\tDPAZ.Z0HKA 6WM.",
	"\tZPR3.TAHVF   6WM.",
	"\t6EZLEV  6WM.",
	"\tJ0LY4.HAZPADY 6WM.",
	"\tTEMHFN CAD  6WM.",
	"\tZEP0NCK.CAD 6WM. ",
	"\tTEMH.PENC 6WM.",
	"\tZEP0N.PENC 6WM",
	"\tMY3FKA OECTNBALR TEMH.CAD  ",
	"\tMY3FKA BECTNBALR ZEP0N.CAD.",
	"\t4A0 CAD     6WM.",

	"\tC06FT. 6WM",
	"\t04NCTNTS    CE.",
	"\tYB.CK0P0CTS.",
	"\tHEYR3BNM0CTS    CE.",
	"\tT0JNTS   CE.",
	"\t1   CE.",
	"\tJP0D0LWEHNE     CE.",

	"\tMY3FKA HA3B.",
	"\tMEHU QKPAHA 6WM.",
	"\t06Y4EHNE 6WM.",

	"\t3ELEH.X0LM 6WM.",

	/* Unlock stuff messages */

	"\tBF6EPETE CVEHY N3 NCT0PNN\nZEP0R               ",
	"\tBF6EPETE BPEMR ATAKN  \n60CC-CTADNN B NCT0PNN ZEP0R   ",
	"\tBF6EPETE CVEHY N3 NCT0PNN\nN3 TEMH0N NCT0PNN   ",
	"\tBF6EPETE BPEMR ATAKN  \nB0CC-CTADNR B TEMH0N NCT0PNN  ",
	"\tBCE BPEMR ATAKN B CTADNN   \nTEJEPS D0CTYJH0   ",
	"\tMNHN NZPA: KAPT PENC B TPEX  \nHAJPABLEHNRX D0CTYJHA    ",
	"\tMNHN NZPA: KAPT PENC   2P\nBEPCNR D0CTYJHA         ",
	"\tMNCCNN 3BYK0B JP0NDEHF!!!!!!        \nBF6EPNTE PA3HFE 3BYKN B     \n3BYK0B0M   2P PEWNME      ",
	"\tMNCCNR XB0CT0B JP0NDEHF!!!!!!!      \nBF6EPNTE PA3HFE MAGNHF B      \nXB0CT0B0M 2P PEWNME.    ",
	"\tMNCCNN K0CTRGEK JP0NDEHF!!!!!!!!!      \nBF6EPN PA3HFE K0CTRGKN B       \nK0CTRGKNH0M  2P PEWNME      ",
	"\tMNCCNN TEHEN JP0NDEHF!!!!!!!!!!!!     \nBF6EPNTE PA3HFE TEHN B       \nTEHEB0M     2P   PEWNME    ",
	"\tMNCCNN QZMQHA JP0NDEHF!!!!!!!!!!!!    \nBF6EPNTE PA3HFE MAGNHF B      \nB QZMAHCK0M 2P PEWNME      ",
	"\tMNCCNN PYMRH JP0NDEHF!!!!!!!!!!!!!1  \nBF6EPNTE DPYZNE PYMRHA B    \nPEWNME PYMRH    2P.            ",
	"\tMNCCNN 3BYK0B JP0NDEHF C  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \n3BYK0B0M   2P PEWNME      ",
	"\tMNCCNN XB0CT0B JP0NDEHF  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB PEWNME  2P XB0CT0B.    ",
	"\tJP0NDEHF BCE K0CTRGKNHF     \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nK0CTRGKNH0M  2P PEWNME      ",
	"\tJP0NDEHF BCE MNCCNN TEHEN  \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nTEHEB0M     2P   PEWNME    ",
	"\tJP0NDEHF BCE QZMAHCKNE     \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB QZMAHCK0M 2P PEWNME      ",
	"\tJP0NDEHF BCE MNCCNN PYMRH \nPAHZ0M \"A\".            ",
	"\tBF6EPNTE H0B0E             \nB PEWNME   2P PYMRH.      ",
	"\tJ03DPABLEHNR!   \nBF C06PALN BCE QM6LEMF!!!        \nH0BAR CTADNR D0CTYJHA.",

	/* Hero story scene select */

	"HA4AL0       ",
	"BX0D K0CTRGKN ",
	"CJACEHNE 3BYK.",
	"TUPEM.0CTP0B \n6EWATS",
	"0TJ0P   \nC TEHRMN   ",
	"Z0PA JPNBEDEH.",
	"MNP0B.Z0CJ0DCTB0",
	"B0DHAR MNHA ",
	"ZDE QZMQH?     ",
	"QZMQH...\nCKPFT.6A3A ",
	"K0CM0 CTAPT      ",
	"K0CM0K0L0HNR\n\"APK\"",
	"J0CL.4ACTS    \nEMEPALSDA     ",
	"C0HNK B TPEB0ZE ",
	"J0CL. GAHC ",

	/* Dark story scene select */

	"HA4AL0       ",
	"BB0D PYMRH ",
	"CKPFT.6A3A \nCH0BA!",
	"TEHS J0CLED. ",
	"0TONLSTP0B\nCKPFT.6A3A ",
	"C06NPAHNE\nTEMHFX     ",
	"D0C\nXA0C N3YMPYD ",
	"0TJ0P   \nC C0HNK0M ",
	"QZMQH     \nNMJEPN",
	"J0CL\nXA0C N3YMPYD ",
	"CKPFT.6A3A \nJEPEXBAT ",
	"0TJ0P   \nC K0CTRGKAMN ",
	"JLAH QZMAHA  ",
	"TANHA  \nTEHEN    ",
	"J0CLEDHRR 6NTBA",

	/* Last story scene select */

	"HA4AL0       ",
	"J0CLEDHRR MNCCNR",
	"   \n0CH0BHAR 6NTBA ",
	"HADEWDF       ",

	/* World ranking and network connection stuff (unused) */

	"HAWMN Y DLR 06H0BLEHNR DATF.  ",
	"BPEMR ATAKN MNP0B. PAHZA ",
	"04KN ATAKN MNP0B0Z0 PAHZA ",
	"QM6LEMA MNP0B.PAHZA ",
	"06GNN PAHZ   ",
	"J0KA3ATS CTADNN         ",
	"J0KA3ATS CTADNN         ",
	"PEDAKT.K0MMEHTAPNN",
	"\tCETEBAR-PEZNCTPAVNR - HE06X0DNM0\nB0NTN B MNP0B0N PAHZ.   ",
	"\tNCJ0LS30BATS J0CLEDHNN 6PAY3EP\nB CETN.        ",
	"\tC0EDNHEHNE C NHTEPHET      ",
	"\tD0 T0Z0 KAK BF B0NDETE B CETS, \nHAD0   3AJLATNTS    TELEO0HHFN \nZ0H0PAP ISP CBR3N.          \nECLN BF NCJ0LS3YETE  ISAO Net \nC TELEO0HA HA4NHAUGEZ0CR C 0990,   \nTELEO0HHAR JLATA 6YDET 10 NEH 3A    \nTPN MNHYTF B C00TBETCTBNN C       \nDNAL          Q2 CNCTEM0N\nJPNGLNTE PYK0B0DCTB0  \nDLR 60LSGEN NHO0PMAV.",
	"\tC0EDNHNTSCR?           ",
	"\t<DA ><HE>",
	"\tC0EDNHEHNE C NHTEPHET N   ",
	"\tD0 T0Z0 KAK BF B0NDETE B CETS, \nHAD0   3AJLATNTS    TELEO0HHFN \nNCJ CBR3S                  \nC0EDNHNTSCR?           ",
	"\t<DA ><HE>",
	"\tHA60P   ||",
	"\t<0TMEHA>",
	"\tBBEDN \"NCJ\" NMR N JAP0LS   ",
	"ID<++>",
	"JAP0LS  <++>",
	"\tHE M0ZY HANTN M0DEM. ",
	"\tJP0BEPKA C0EDNHEHNR.   ",
	"\tLNHNR 3AHRTA     ",
	"\tHA60P CLEDYGEZ0 H0MEPA.   ",
	"\tLNHNR 3AHRTA     ",
	"\tJ0JP06YNTE J03WE.      ",
	"\tLNHNR 3AHRTA     ",
	"\tJP0BEPKA YCTAH0B0K   ",
	"\tHEB03M0WH0     ",
	"\tJP0BEPKA M0DYLSH0N CBR3N, NLN  \nYCTAH0B0K M0DEMA  ",
	"\tHELS3R C0EDEHNTSCR. LNHNR 3AHRTA.   \nJP0BEPS HACTP0NKN M0DEMA N      \nJ0JP06YN J03WE.      ",
	"\tHEB03M0WH0 C0EDNHNTSCR       \nCEPBEP BEPHYL 0GN6KY.        ",
	"\tJP0BEPS NMR N JAP0LS  ",
	"\t0TC0EDNHRTS J0KA HE AKTNBHFN    ",
	"\tJ0KA C0EDNHRETCR, Y TE6R 3AHRT TELEO0H                         \n    \nC0EDNHNTSCR?           ",
	"\tC0EDNHEHNE C C0HNK-CETSU           ",
	"\tCEPBEP 3AHRT       ",
	"\tJ0JP06YN J0DC0EDNHNTSCR J03WE     ",
	"\t06H0BN 6A3Y DAHHFX     \nQT0 M0WET 3AHRTS HECK0LSK0 MNH",
	"<0TMEHA>",
	"\t0TMEHNTS C0EDNHEHNE?   ",
	"<DA ><HE>",
	"\tYBEPEHF 4T0 X0TNTE 0TC0EDNHNTSCR?   ",
	"<DA ><HE>",
	"\tPAHZ YBELN4EH D0 H0MEPA   \n06GEZ0 <++> PAHZA.           ",
	"\tBAG PAHZ 6FL YMEHSGEH     \n06GEZ0 <++> PAHZA.           ",
	"\tBAG PAHZ 6FL YBELN4EH        \n06GEZ0 <++> B  <++> 04KN ATAKN   ",
	"\tBAG PAHZ 6FL YBELN4EH        \n06GEZ0 <++> B  <++> BPEMR ATAKN ",
	"\tPAHZ YBELN4EH D0 H0MEPA   \n06GEZ0 <++> QM6LEMF PAHZA.    ",
	"\tBAG PAHZ 6FL YMEHSGEH        \n06GEZ0 <++> B  <++> 04KN ATAKN   ",
	"\tBAG PAHZ 6FL YMEHSGEH        \n06GEZ0 <++> B  <++> BPEMR ATAKN ",
	"\tBAG PAHZ 6FL YMEHSGEH     \n06GEZ0 <++> QM6LEMF PAHZA.    ",
	"<++>",
	"\tNCJ0LS30BATS T0T E-MAIL\nDLR J0DTBEPWDEHNR\n(M0WH0 YCTAH0BNTS E-MAIL   \nHA 0TJPABKY J03WE.       )",
	"<DA ><HE>",
	"\tHE E-mail YCTAH0BKA HA DPNMKQCT",
	"\tNCJ.H0BENGNN 6PAY3EP DLR    \nHACTP0EK E-MAIL",
	"TF BBEL <++>?",
	"\tJAP0LS.             ",
	"\t<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\tJAP0LS HEBEPHFN.            \nBBEDNTE JAP0LS CH0BA.",
	"<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\t0T0CLATS BAM JAP0LS HA\nHA                E-mail?",
	"<DA ><HE>",
	"\t6YDET 0TJPABLEH0\nHA BAG E-MAIL ADPEC. \nJP0BEPSTE J04TY.       ",
	"\tD06P0 J0WAL0BATS B CETS-C0HNK",
	"\tBBEDNTE NMR.         ",
	"\t12 CNMB0L0B MAKCNMYM \nDLNHF DLR NMEHN.     ",
	"<BB0D > <0TMEHA>",
	"<++>",
	"\tTAK0E NMR YWE CYGECTBYET.",
	"\tBBEDNTE JAP0LS ECLN  \nX0TNTE NCJ0LS30BATS QT0 NMR",
	"<BB0D ><0TMEHA><3A6FL JAP0LS   >",
	"\tDALEE, BB0D JAP0LR.  ",
	"\tMNHNMALSHAR DLNHA JAP0LR 5  \nCNMB0L0B, MAKCNMYM - 12.  ",
	"<BB0D ><BEPH>",
	"\tBBEDNTE    E-MAIL  ",
	"\tECLN BF 3A6YDETE JAP0LS, T0  \n0H M0WET 6FTS BFCLAH J0 E-MAILY.   ",
	"<BB0D ><0TMEHA>",
	"\tX0TNTE DELNTS BAG E-MAIL C      \nDPYZNMN J0LS30BATELRMN?  \nECLN HET, BF6EPNTE \"HET\". ",
	"<DA ><HE>",
	"\tBF6EPNTE CTPAHY N PAN0H\nZDE BF WNBETE. ",
	"CTPAHA: <++>",
	"PAN0H<++>",
	"<BB0D ><0TMEHA>",
	"\tCETS C0HNK MECT0 ZDE M0WH0 06MEHRTSCR\nNHO0PMAVNEN C DPYZNMN J0LS30BATELRMN \nJ0 BCEMY MNPY.  J0WALYNCTA,    \nBEDNTE CE6R VNBNLN30BAHH0.         \nJPEDYJPEWDEHNR M0ZYT NCX0DNTS 0T   \nJ0LS30BATELR, 0HN MYZYT HE     \nNCJ0LS30BATS HAG CEPBEP ECLN 3DECS\n6YDYT WECT0KNE JPABNLA.    ",
	"",
	"<++>'s ",
	"PEZNCTPAVNR 3ABEPGEHA.",
	"\tJ0KA3ATS PAHZN C BEPXY.      ",
	"\t0C06FE PAHZN.          ",
	"\tNCKATS PAHZ J0 NMEHN.       ",
	"\tCJNC0K CTPAH NLN PAN0H0B.       ",
	"\tBBEDNTE PACCTAH0BKY           ",
	"<++>",
	"\tBBENDE NMR K0T0P0E HAD0 HANTN.     ",
	"<++>",
	"\tBBEDNTE CTPAHY                 ",
	"CTPAHA <++>",
	"PANH<++>",
	"<BB0D ><0TMEHA>",
	"\tNHO0PMAVNR J0LS30BATELR      ",
	"\tHAWMN B DLR T0Z0    \n4T0SF BEPHYTSCR     ",

	/* Hero story recaps */

	//City Escape
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"HEK0T0PFE B0NCKA 6FLN 06HAPYWEHF    \nN 0HN CKA3ALN 4T0 NCKALN MEHR.     \nJ0X0WE 0HN M0ZYT B3RTS MEHR    \nHA JP0ZYLKY KYDA-HN6YDS!",
	"QN!4T0 QT0? DNK006PA3?      \nJ0D0WDN-KA!!  \n0 4EM TF Z0B0PNGS?         \nR HE DE3EPTNP N3       \nB0EHHFX CNL!          ",
	"R DYMAL 4T0 QT0 KAKAR-T0     \nGYTKA, H0 QT0 HE CMEGH0!      ",
	"R C06NPAUCS YNTN 0T CUDA",

	//Big Foot
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"4T0 3A CBR3KA TRWELFX  \nZ0L0BEGEK! H0 KT0 0HN B    \nDENCTBNTELSH0CTN?        ",
	"0HN HE T0LSK0 0X0TRTCR 3A   \nMH0N DHEM N H04SU, H0 0HN  \nB3RLN B ZP0MADH0M P060TE  \n4T06 J0NMATS. ",
	"DYMAU 0HN JPABDA PEGNLN           \n3A6PATS MEHR!       ",
	"H0 0HN 4T0 JPABDA BEPRT 4T0 QT0   \nCPA60TAET? R J0KAWY NM K0E-  \n4T0......T0LSK0 DAN MHE TPN   \nMNHYTF C0EDNHNTSCR!          ",

	//Wild Canyon
	"R K0CTRGKN NGNHDF.       \nH0 M0WEGS 3BATS MEHR K0CTRGKN",
	"0DHAWDF, MACTEP N3YMPYD  6FL  \nYKPADEH C 0CTP0BA AHZEL0B.   ",
	"B0P 0KA3ALCR BCE3HANK0N  \nDEB04K0N LETY4EN MFGSU   \nN3 BCEX BEGEN.",
	"K0ZDA QTA DEB04KA MEHR HACTNZHET\nKT0 KAK TF DYMAEGS 06HAPYWNTCR?  \nDA, JPABNLSH0, QZMAH!     \n0H JPNGEL B0 BPEMR 0ZPA6LEHNR\nM0N JLAH N J0JFTATSCR B3RTS   \nMACTEPA N3YMPYDA!  ",
	"R PEGNL PA36NTS       \nMACTEP N3YMPYD HA KYCKN   \nD0 T0Z0 KAK QZMAH PEGNL \n6EWATS. CEN4AC R D0LWEH NX\nHANTN.     ",
	"QTA DEB40HKA LETY4AR  \nMFGS T0WE.         \nMHE HAD0 C06PATS NX N J0L0WNTS    \nN3YMPYD HA3AD 04EHS 6FCTP0!       ",

	//Eggman 1
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R CM0TPEL TB N YCLFGAL    \nH0B0CTN.                   \nR 6FL G0KNP0BAH YBN-\nDEB C0HNKA. ",
	"C0HNK APECT0BAH 3A 4T0\nT0 DENCTBNTELSH0 YWACH0E, \n4T0 HE J0X0WE HA C0HNKA.",
	"R HE M0Z J0BEPNTS 4T0 QT0 TAK, \nJ0QT0MY AW J0DJPFZHYL N      \nJ0JAL JPRM0 HA TUPEMHFN\n0CTP0B.       ",
	"YZADAN KAK?              \nQZMAH! 0H CH0BA C0 CB0NMN  \n3L06HFMN GTY4KAMN!       \nQT0 HE X0P0G0!     ",
	"OK, BPEMR BFPBATS H0BFN  \nT0PHAD0 N CJACTN QMN!    ",
	"JPEBPAGEHNE T0PHAD0!   ",

	//Prison Lane
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R M0Z 6F CJACTN QMN 0T QZMAHA, H0  \n0HA CKA3ALA, 4T0 QZMAH CH0BA C0  \nCB0NMN 3LFMN D0P0ZAMN, JLAHNPYET\n4T0-T0 DENCTBNTELSH0 60LSG0E!  ",
	"HAD0 CLEDNTS 3A QZMAH0M, H0    \nCHA4ALA HAD0 CJACTN KP0GKY,     \nC0HNK!",
	"4T0 QT0?    \nTF X04EGS T0WE?    \nHY, ECLN TF JPABDA X04EGS,\nT0 R HE JP0TNB. \nH0 HE CT0N HA M0EM JYTN! ",

	//Metal Harbor
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"4T0 B QT0M MNPE     \nAMN DELAET 3DEC",
	"HE HAGE DEL0.....HAD0 HANTN QTZ0   \n4EPH0Z0 DNK006PA3A, K0T0PFN    \nJ0X0W HA M0U TEHS! 0H ZDE-\nT0 HA 0CTP0BE,           \nR 3HAU QT0",
	"R TPA4Y 3DECS CB0E BPEMR!\nR 06MAHY 0XPAHY N YDAP        \nD0LWEH 6FTS J0 CTFKY!     ",
	"T0 ECTS R CEN4AC   \nDE3EPTNP?          ",

	//Shadow 1
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"J06EZ N3 TUPSMF -  \nHET JP06LEM!   \nN R T0WE HAGEL TEHS!       ",
	"0H HE Y6EWNT HA QT0T PA3!    ",

	//Green Forest
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"R J04TN HAGEL TEHS \nH0 R T0P0JNLCR.       \nLY4GE DENCTB0BATS N 6FCTP0\n\nQZMAH CKA3AL 4T0      \nYCTAH0BNL CBR3S MEHEE \n4EM 3A JRTS MNHYT!        ",
	"QZMAH CKA3AL 4T0      \nYCTAH0BNL CBR3S MEHEE \n4EM 3A JRTS MNHYT!        ", //unused
	"R D0LWEH EXATS HA QT0T\n0CTP0B N 6FCTP0! \nZDE QMN N XB0CT!       ",

	//Pumpkin Hill
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"CLEDYR CLA60MY CNZHALY  \nJ0LY4EHH0MY 0T MACTEPA\nN3YMPYDA, R HAGEL      \nCE6R B QT0M CELSCK0M KAHS0HE",
	"04EHS ZADK0, H0 R HE \n60UCS JPNBNDEHNN!        ",
	"R D0LWEH HANTN KYCKN     \nN3YMPYDA HEMEDLEHH0!      ",

	//Mission Street
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"QZMAH 06SRBNL CB0N   \n3L0N JLAH Z0CJ0DCTBA  \nHAD BCEM MNP0M!",
	"0H JP0CT0B30PBAL J0L LYHF    \nQTNM M0GHFM 0PYWNEM N    \nTEJEPS ZP03NTSCR 3AXBATNTS \nBCU JLAHETY!         \nR YBEPEH, 4T0 QT0Z0 HE CLY4NTCR! ",
	"QZMAH J0DKLU4AETCR K     \nQHEPZNN XA0CA N3YMPYDA DLR  \nYBELN4EHNR M0GH0CTN.  ",
	"TEJEPS QT0 3A MH0N\nR HANDY QZMAHA N    \nXA0C N3YMPYD0B!    ",
	"CHA4ALA HAD0 HANTN   \nHADEWH0E MECT0!      ",

	//Aquatic Mine
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"CLEDYR 3A CNZHAL0M  \n0T MACTEPA N3YMPYDA, R  \nHAGEL CB0N ZLY6NHF BHYTPN \nQT0Z0 KAHS0H",
	"QT0 MECT0 J0X0WE HA  \nJYCTFHU NLN BP0DE T0Z0.      \n60LSGAR 4ACTS J0D B0D0N!    ",
	"HYWH0 HANTN KYCKN             \nMACTEPA          \nN3YMPYDA 3DECS.     \nHET BPEMEHN QT0 06CYWDATS!   ",
	"HAD0 HANTN QTN KYCKN        \nKAK M0WH0 6FCTPEE!         ",

	//Route 101
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"R CLED0BAL 3A       \nCNZHAL0M 0T XA0CA N3YM-\nPYDA QZMAHA.       ",
	"4T0 QZMAH 6YDET    \nDELATS B K0CM0C",
	"HE 6ECJ0K0NCR\nR HANDY T04H0E PACJ0L0WEH-\nNE QZMAHA N 04EHS CK0P0!     ",
	"HE JEPEWNBAN,QMN\nJ0MHN, R \"L0BKA4\" K0ZDA   \nJPNX0DRT MEXAHN4ECKNE BEGN!    ",
	"R HANDY JPE3NDEHTA!     ",

	//Hidden Base
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"MF EXALN B JPE3NDEHTCK0M  \nLNM0 N YZADAN 4T0?  \nMF HAGLN ZDE QZMAH   \nJPR4ETCR! ",
	"QZMAH N EZ0 JPNRTELN  \nB K0CMN4ECK0N K0L0HNN, APK.  ",
	"CLEDYUGNN GAZ - HANTN CEKPET-\nHYU 6A3Y QZMAHA,    \nZDE-T0 B JYCTFHE!       ",
	"DABAN! R J0NDY JEPBFN N  \nHANDY BX0D.       ",

	//Pyramid Cave
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"MF PEGNLN JP6PATS- \nCR B JNPAMNDY N HANTN    \n6A3Y QZMAHA!         ",
	"ECTS D0P0ZA 4T06F         \nJ0JACTS B K0CM0C 0TCUDA.     \nY HAC HET BPEMEHN,      \nJ0GLN!   ",

	//Death Chamber
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"MF CM0ZLN 06HAPYWNTS  \nCEKPETHYU 6A3Y QZMAHA\nB ZLY6NHE JNPAMNDF.     ",
	"TEJEPS HAM HAD0    \nHANTN KLU4 0T DBEPN,     \n4T06F J0JACTS TYDA.      ",
	"4T0? J04EMY R D0LWEH  \nNCKATS QT0T KLU4? QT0 HE M0R PA- \n60TA, H0 R CDELAU.\nR D0LWEH J0T0MY 4T0   \nQT0 DLR MACTEPA N3YMPYD",
	"R J0KAWY TE6E YMEHNR    \nK0T0PFE DELAUT  \nMEHR VEHHFM 0X0THNK0M!   ",

	//King Boom Boo
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"QT0 LAK0MFN KYC04EK!     \nR HAGEL KLU4 N TEJEPS  \nBPEMR N3Y4NTS CEKPETHYU 6A3Y \nQZMAHA.     ",
	"4T0 QT0 6FL0? \nY MEHR JL0X0E JPED4YBCTBNE!       \nKAK 3DECS MEP3K0. 3DECS M0ZLN   \n6FTS DYGN TEX CTPAWEN M0ZNL?    ",
	"HE DYMAU R M0ZY D0Z0B0- \nPNTSCR...H0 T0ZDA KAK   \nR HANDY KYCKN         \nN3YMPYDA?             \n4EPT, Y MEHR HET BF60PA",

	//Egg Golem (hero)
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"CJACN60 K0CTRGKAM, \nMF CM0ZLN 0TKPFTS DBEPS   \nK CEKPETH0N 6A3E QZMAHA.     ",
	"HEN3BECTH0 0TKYDA  0H\nJ0RBNLCR N ZP0MADHAR CTA- \nTYR 0WNLA! ",
	"4EPT0BA EZ0 Z0L0BA\nKAK 0H Y3HAL   \n4T0 MF JPNDEM? ",
	"TF JPADA DYMAEGS 4T0 KY-\nC0K KAMHR M0WET 0CTAH0BNTS",

	//Eternal Engine
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"MF JP0BELN T0K        \n0T CEKPETH0N 6A3F QZMAHA N     \nHAK0HEV-T0 JPN6FLN B K0CMN4EC- \nKYU K0L0HNU, APK.        ",
	"M0R NDER-YHN4T0WNTS 0PY- \nWNE NCJ0LS3YUGEE     \nJ0DDELSHFN N3YMPYD! ",
	"NHTEPECH0, C0HNK \nJ0NMET JLAH?         ",
	"HANTN CNLY               \nN KAK M0WH0 CK0PEE!   ",

	//Meteor Herd
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"KYCKN MACTEPA    \nN3YMPYDA MH0N C06PAHHFE,  \nTEJEPS JLABAUT B K0CM0CE. \nHAM CLED0BAL0 6F      \n0XPAHRTS NX       \nLY4GE!            ",
	"QT0 HE LEZKAR PA60TA\n3AGNTA MACTEPA N3YMPY\nDA, TF 3HAEGS QT0?",
	"R D0LWEH HANTN NX D0 T0Z0 \nKAK MF NX J0TEPREM.",

	//Rouge
	"R K0CTRGKN NGNHDF.       \n30BN MEHR K0CTRGKN.   ",
	"J0CLE HAX0WDEHNR J0L0BNHF\nKYCK0B MACTEPA N3YMPYD0B, R  \nJPNDY K T0N DEB40HKE, CH0BA!    ",
	"YBEPEH, Y HEE DPYZAR   \nJ0L0BNHA.          \nHET BPEMEHN 60LTATS!   \nR HE DAM EN HN GAHCA!       ",
	"R BEPHYL TE KYCKN    \n06PATH0!    ",

	//Crazy Gadget
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"HAG JLAH C0BEPGEHEH, \nJ0KA 0H  DEPWNT QMN!      ",
	"QZMAH CKA3AL 4T0 J0MEHRET \nQMN HA N3YMPYD........\nR YWE DYMAL 06 QT0M!           ",
	"HE BPEMR GYTNTS!          \nQZMAH Z0T0B CH0BA     \nNCJ0LS30BATS 0PYW!",
	"XB0CTF,QMN, DEPWNCS\nR NDY!     ",

	//Eggman 2
	"MEHR 30BYT CNLSHFN MANL,\nH0 BCE 30BYT MEHR XB0CT.    ",
	"C0HNK 3AXBA4EH N      \nYJAK0BAH B KAJCYLY. QZMAH  \nBFCTPELNT KAJCYLY B K0CM0C \nN B30PBET EE!   ",
	"HET, QT0 HE JPABDA!  \nC0HNK HE YMPET!     ",
	"QZMAH! R HE J03B0LU    \nYNTN C QTNM!       \nR 06EGAL C0HNKY 4T0 HE     \n6P0GY N R HE 6P0GY. \nTF 3AJLATNGS 3A QT0!       ",

	//Final Rush
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"R NCJ0LS3YU    \nXA0C K0HTP0LS, N    \nYDEPY N3 L0BYGKN     \nQZMAHA!            ",
	"Y HAC HE TAK MH0Z0 BPEMEHN\nD0 T0Z0 KAK 0PYWNE 3ADENCTB. !",
	"R NCJ0LS3YU GAHC N  \n6P0GY QT0T N3YMPYD B JYGKY \nD0 T0Z0 KAK 0HA BFCTPELNT!!",

	//Shadow 2
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"K00PDNHAVNR HE JL0XA!    \nJP0CT0 K0ZDA R DYMAL BCE \n6FL0 J0D K0HTP0LEM, TEHN \nJ0RBNLNCS.       \nHAD0 3AK0H4NTS CPAWEHNE  \nJP0TNB 4EPH0Z0 DNK006PA3A,CEN4AC!",
	"J0KAWNTE 4T0 M0WETE, TEHN!   \nPEALSHAR M0GS....KLACC!!",

	/* Dark story recaps */

	//Iron Gate
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"CLY4ANH0, R \nHAGEL DHEBHNK DEDYGKN.         \nB HEM, 0H 0JNCAL MNCTN4ECKNN    \nCEKPET 0PYWNE K0T0P0Z0  \n0H HA3FBAL \"JP0EKT TEHS\".          ",
	"DHEBHNK J0X0WE 6FL 3AKPFT BHYTPN   \nB0EHH0-NCCLED0BATELSCK0M VEHTPE K0ZDA\n0H 6FL 3AKPFT.       \n50 LET HA3AD.     ",
	"6ECJ0LE3H0E NCCLED0BAHNE!     ",
	"HACLEDNE BELN4ANGEZ0 Y4EH0Z0 M03ZA   \nB NCT0PNN MNPA, JP0OECC0P        \nZEPALSD. QT0 M0N DEDYGKA!!!         ",
	"R D0LWEH B0CJ0LS30-\nBATSCR QTNM!       ",

	//Hot Shot
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"PA36YWEH N3 ZLY60K0Z0   \nCHA, DLNBGEZ0CR 50 LET.   ",
	"D0KT0P QZMAH, \nBHYK M0EZ0 C03DATELR, JP0O.\nZEPALSD 0CB060DNL MEHR.       ",
	"D0KT0P PA36YDNL MEHR  \nN J0QT0MY, R BFJ0LHNL EZ0   \nJP0CS6Y.   ",
	"CHA4ALA, R J0KAWY CNLY\nK0T0P0N R BLADEU.    \n3A 10 CEKYHD R M0Z       \nYHN4T0WNTS B0EHH0E CHAPRWEHNE   \nKAK NZPYGKY!      ",

	//Dry Lagoon
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R JP0CT0 LU6LU DPAZ0VEHH0CTN N\nHE BNWY D0CTAT04H0Z0 K0L-BA\nR HAGEL 04EHS VEHHFN      \nMACTEP N3YMPYD H0....",
	"QT0 CLEDYET          \n3A MH0N.              \n0H TAK HACT04NB!   ",
	"KP0ME T0Z0 QT0T CTPAHHFN MYW- \n4NHA CTPAHH0 CM0TPRGNN HA YCF \n3A6PAL  EZ0 Y MEHR, H0 D0  \nT0Z0 KAK QT0 CLY4NL0CS,  \n0H PALETELCR HA KYC04KN.     ",
	"0X, 4T0 TF HADELAL!       ",
	"TEJEPS R D0LWEH HANTN N\nC06PATS BCE KYCKN BMECTE!!",

	//Sand Ocean
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R N36ABNL TEHS 0T     \nB0EHH0Z0 CPEDCTBA H0          \nTEJEPS....",
	"TEHS CKA3ALA B3RTS     \nN3YMPYD XA0CA N BEPHYTS   \nEZ0 B K0CM0K0L0HNU, APK.     ",
	"D0LWH0 6FTS 4T0-T0 JP0NCX0DNT.   \nMHE CLEDYET BEPHYTSCR K 6A3E\nN JP0BEPNTS QT0!!",

	//Radical Highway
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"R 3A6PAL N3YMPYD XA0CA N3    \nHAVN0HALSH0Z0 PE3EPB.6AHKA",
	"N TEJEPS B0EHHFE N J0LN-\nVNR 0X0TRTCR 3A MH0N. \nMHE HAJLEBATS ECLN 0HN 3HAUT KT0 R\nTAK KAK HNK0ZDA HE J0NMAUT MEHR\nR JP0CT0 J0TEPRL BPEMR!   ",
	"HET BPEMEHN B NZPF NZPATS.\nR D0LWEH Y6PATSCR 0TCUDA, 6FCTP0",

	//Egg Quarters
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R CM0Z J0L0WNTS TPAHCMNTTEP B  \nTY MAGNHY CTAP0Z0 MYW4NHF\nK0ZDA 0H BJEPBFE JPNGEL",
	"HE M0ZY CKA3ATS J04EMY...J0KA.  ",
	"J0T0M R JP0CLEDNL 3A HNM D0\nQT0N JNPAMNDF, H0 HE\nCM0Z B0NTN, J0T0MY 4T0     \nDBEPS 6FLA 3AKPFTA. ",
	"XMM, M0WET HAD0 HANTN    \nKLU4 NLN 4T0-T0 J0D06H0E.    ",

	//Lost Colony
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R J0GEL B K0CM0K0L0HNU, APK,KAK\nCKA3ALA MHE TEHS.       ",
	"4T0 B VEHTPALSH0M J0MEGEHNN  \nAPK?            \nHAD0 BFRCHNTS QT0! ",

	//Weapons Bed
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"DEB40HKA, P0DW,     \nC0EDNHNLA  HAGY CNLY \nN MF BEPHYLNCS B TUPEMH.0CTP0B",
	"MF 3DECS 4T06F HANTN  \nN3YMPYD XA0CA,    \nK0T0PFN XPAHNTCR ZDE-T0 \nB B0EHH0-NCCLED0BATELSCK0M VEHTPE.",
	"R J0NDY JEPBFM N     \n0TBLEKY C0LDAT.     \nXA...T0ZDA MF 3ABEPGNM HAGA JLAHF!    ",

	//Tails 1
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"K0ZDA MF 6YDEM TAM \n4T06F D0CTATS N3YMPYD     \nXA0CA, KT0-T0 TAM 6YDET  \n4T06F 0CTAH0BNTS HAC!        ",
	"TEHS, P0DW, BJEPED!    \nR J03A604YCS 0 HEM!    ",
	"Y6NTS TE6R - DLR MEHR \nYD0B0LSCTBNE!     ",

	//Security Hall
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"R BHYTPN        \nB0EHH0-NCCLED0BATELSCK0Z0, \nD0KT0P JLAHNP0BAL QT0.        ",
	"HAD0 HANTN TPN          \n0CTABGNXCR N3YMPYDA XA0CA\nQT0 D0LWH0 6FTS KYC04EK!       ",

	//Flying Dog
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"MALFN HA60P.     \nKAK R M0Z J03B0LNTS  \nCLY4NTSCR QT0MY C0 MH0N",
	"J0CLE C06PAHNR TPEX \nN3YMPYD0B XA0CA, 4T0-\nT0 J0JAL0 B M0N ZLA3A!  \nTAK BHE3AJH0......",
	"CNZHALN3AVNR 0TKLU4EHA N R \n6FL J0NMAH B            \nL0BYGKY! ",
	"N3 HN0TKYDA JPNGEL  \nQT0T C BNDY CNLSHFN 60EV.         \nY HAC HE TAK MH0Z0 BPEMEHN\nD0 T0Z0 KAK 60M6A          \nCPAS60TALA!  \n0X, JP0CT0 QT0 HE M0N DEHS! ",
	"CHA4A-\nLA HAD0 J03A60TNTSCR 0 DELAX.     ",

	//White Jungle
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"J0X0WE TA DEB40HKA     \nJP0NZPALA CB0E DEL0.           ",
	"0HA MHE HE 6E3PA3LN4HA, \nQT0 N3YMPYD XA0CA,       \nK0T0PFN HAD0 C0XPAHNTS. ",
	"HAD0 CJEGNTS J0T0MY 4T0 HE TAK \nMH0Z0 BPEMEHN 0CTAL0CS D0\nT0Z0 KAK 60M6A 6AX",

	//Sonic 1
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"J0RBNLNCS DPYZNE DNK006PA3F \nJ0KA R 6FL HA JYTN K \nCJACEHNU P0DWA. ",
	"0H HA4NHAET PA3DPAWATS MEHR. \nBPEMR J0KA3ATS PEALSHYU CNLY!   ",

	//Route 280
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"MF 06SRBNLN HAG JLAH MNP0-\nB0Z0 Z0CJ0DCTBA NCJ0LS3YR \nCNLY N3YMPYD0B XA0CA YKPA- \nDEHHFX HAMN NX B0EHH0-NCC-\nLED0BATELSCK0Z0.  ",
	"3APRWATS JYGKY 3ATMEHNR    \n04EHS D0LZ0!       ",
	"J0QT0MY HAD0 D0CTATS   \nJ0CLEDHNN N3YMPYD 6FCTP0!   \nZDE QT0T B0PNGKA?     ",

	//Sky Rail
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"R J0CLAL C006GEHNE P0DWY \n4T06 0H CLED0BAL QT0MY JLAHY.\nY JNL0TA ECTS J0CLEDHNN   \nN3YMPYD XA0CA.            ",
	"3DECS TAK MH0Z0 BF3FBAU-\nGNX CTPAX Z0P BJEPEDN MEHR......\nJYCTRKN, R HE   \nJ03B0LU CAM0LETY YLETETS!      ",

	//Egg Golem (dark)
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"R WDY C0HNKA HA M0EN TANH0N  \n6A3E, 4T06F J0KA3ATS EMY  \nP060TA C03DAHH0Z0 DLR       \nYCTPAGEHNR, H0.................",
	"QT0T Z0LY6.DNK006PA3 CH0BA CCFLAETCR\nCEN4AC EZ0 ATAKYUT N 0H   \nJPNDET K0 MHE J0CLE\n4T0 3DECS BE4H0 JP0NCX0DNT? ",
	"XEN, JP04S C D0P0ZN!   \nC0HNK 6EWAL!     ",

	//Mad Space
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"H0 QT0 HE BCE 4T0 R ......",
	"NTAK, TE JAPHN J0RBNLNCS    \nK0ZDA R BEPHYLCR N3    \nCEKPETH0N MNCNN",
	"QT0 3HA4NT 4T0 0HN C06PALN      \n0CTALSHFE KYCKN MACTEPA       \nN3YMPYDA. QT0 M0N GAHC!   ",
	"R B0CCTAH0BNL NHO0PMAVNU 0 TANH0M   \nJP0EKTE \"TEHS\", TEJEPS QT0   \nM0N GAHC 3AXBATNTS     \nMACTEPA N3YMPYDA N Y6EWATS!!",

	//Knuckles
	"MEHR 30BYT PYMRHAR DY6NHA\nK0T0P0Z0 BCE   \n3HAUT KAK BELNK0Z0 0X0THNKA",
	"0H HA4NHAET MEHR PA3DP0WATS!      \n0H HEYM0LNM HAC4ET    \nMACTEPA N3YMPYDA, HE TAK LN!?\nJ04EMY 0H JP0CT0 HE 6P0CNT? \nQT0 D0CAWDAET.        ",
	"R J0KALE4Y EZ0 N B03SMY    \nMACTEPA N3YMPYDA!  ",

	//Cosmic Wall
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"C0HNKA N EZ0 DPYWK0B \nK0ZDA HANDY KAK J0JACTS B \nK0CM0K0L0HNU.       ",
	"J04EMY MHE HAD0 4NTATS N3 DBYX\n4ACTEN N3YMPYD0B XA0CA?     \n4T0 JP0NCX0DNT!!",
	"0HN HABEPH0 JLAHNPYUT\nK0HTPATAKY.      ",
	"Y MEHR HET BPEMEHN!       \nHA3AD B K0CM0K0L0HNU DLR\nYDAPA J0 HNM.  ",

	//Tails 2
	"R D0KT0P QZMAH, BELN4ANGNN  \nHAY4HFN ZEHNN MNPA!!!!!        ",
	"XAXAXAXAXAXA!\nR CDELAL QT0! R J06EDNL C0HNKA!       \nQT0T DNK006PA3 CEN4AC \nJPNDET HABCEZDA!    \n0H JP0CT0 JLFBY4NN       \nKYC0K B K0CM0CE!    ",
	"4T0 TF 6YDEGS DELATS TEJEPS, TANLC?\nECLN TF JP0TNB MEHR,  \nTF J0CTPADAEGS TAKWE KAK   \nTB0N DPYWKN, C0HNK.  ",

	//Final Chase
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"HAK0HEV-T0 BCE CEMS 4ACTEN N3YMPYDA  \nXA0CA HA MECTE.  \nTEJEPS YCTAH0BLEH0,  \nR J04TN 3AK0H4NL!   ",
	"BCE QT0 BPEMR, KT0-T0 JFTAETCR \nD0CTATS JYGKY 3ATMEHNR.             \nEMY HE4EZ0 DAWE HADERTSCR!  ",
	"BAWH0, 4T06F MF HE D0JYCTNLN\nCEN4AC HNKAK0N 0GN6KN.      \nHAD0 N36ABNTSCR 0T BCEX    \nJAPA3NT0B!  ",

	//Sonic 2
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"QT0 T0T Z0LY60N DNK06PA3 K0T0PFN JF- \nTALCR YHN4T0WNTS HAGY JYGKY!  ",
	"R J0PAWEH.    \nR DYMAL 0H YMEP B KAJCYLE K0T0- \nPYU MF BF6P0CNLN B K0CM0C",
	"TEJEPS R 3HAU 4T0 0H 04EHS    \n0JACEH!      ",
	"K0ZDA R C HNM PA36EPYCS, 0H 6YDET\nWALETS 4T0 HE YMEP B T0N KAJCYLE.  \nR J0KAWY EMY M0U PEALSHYU CNLY.  ",

	/* Last story recaps */

	//Cannon's Core
	"MEHR 30BYT QMN P03A.\nR YMEH N J0L0H QHEPZNN!     ",
	"JP0N30NDET HE4T0 YWACH0E!       \nJP0OECC0P ZEPALSD AKTNBNP0BAL  \nQTY JP0ZPAMMY YWE DABH0.",
	"JPN4NH0N AKTNBAVNN QT0N    \nJP0ZPAMMF 6FLA CC0PA B K0L0HNN \nHA EZ0 0P6NTE. TEJEPS, KPAX 6YDET N HA\n3EMLE!                ",
	"J0X0WE QZMAH 06MAHYL \nTEHS.          ",
	"0H 3L0N D0KT0P!          \nR X04Y KPNKHYTS HA HEZ0,H0 CHA4A\nLA HAD0 0CTAH0BNTS K0CM0K0L0HNU \n0T J0PAWEHNR.",
	"MF PEGNLN 06SEDNHNTS \nN J0NTN B RDP0 K0L0HNN 4T06   \n0CTAH0BNTS CNLY N3YMPYD0B XA0CA.    ",
	"Y HAC 0CTAL0CS MAL0 BPEMEHN!!\nDEPWNTECS........BJEPED!        ",

	//The Biolizard
	"R TEHS DNK006PA3A.      \nEDNHCTBEHHAR WN3HS 0TTYDA.          ",
	"CJACN60 QMN, R CM0Z 3AJ0M\nHNTS WELAHNE MAPNN.      ",
	"K0ZDA R HAK0HEV-T0 0303HAL \nQT0 JP0T0TNJ WN3HN JFTALCR \n0CTAH0BNTS MEHR. ",
	"R J03A604YCS 06 QT0M, C0HNK!    \nJ0CTAPANCR 0CTAH0BNTS CNLY     \nN3YMPYD0B XA0CA.   ",

	//The Finalhazard
	"R C0HNK!  C0HNK DNK006PA3!    ",
	"MF CM0ZLN 0CTAH0BNTS CNLY        \nN3YMPYD0B XA0CA, H0       \nK0CM0K0L0HNR BCE EGE JADAET.  ",
	"QT0T JP0T0TNJ CTAL 0DNH C    \nK0CM0K0L0HNEN N BEDET EE K          \nCT0LKH0BEHNU C 3EMLEN.              ",
	"K0CM0K0L0HNR B0NDET B  3EMHYU    \nATM0COEPY 04EHS CK0P0.      \nHAD0 YHN4T0WNTS EE CEN4AC!",
	"CNLA 3AJPABLEHA KAK         \nJ0WELALN. J03B0LS MHE     \nJ0KA3ATS CYJEP CNLY C0HNKA!"
};

std::vector<const char*> PauseMenuKudos
{
	"\aDALEE   ",
	"\a3AH0B0 ",
	"",
	"",
	"",
	"\aYX0D",
	"",
	"",
	"",
	"",
	"",
	"Are you sure you want\nto restart the stage?\nYour unsaved progress will be lost.", // fix for extra spacing of 2
};